### ISSUE TITLE
Can you tell me how to import your SDK to Swift project?

### ISSUE THREAD

**Issue by xspyhack** [qiniu/objc-sdk#102]
When I use pod to import Qiniu, AFNetworking can't found but AFNetworking had already in my pods project.

When you can push an Swift example? --BY: Nix

**Comment by Kivenhaoyu** [comment]
1:First you should write  pod "Qiniu", "~> 7.0" to your Podfile,then pod install
2:Actually，Swift project can use the same way to pod Qiniu SDK like objective-c,when you import the SDK,you can use "Bridging Header" to contect the two codes,Here is an example to upload an image named playLogo with Swift
 
    func UpLoad()
    {
        var mutable : NSMutableDictionary = NSMutableDictionary()
        let manager = QNUploadManager()
        let imageData = UIImagePNGRepresentation(UIImage(named: "playLogo")!)
        manager .putData(imageData, key: "your key", token: "your token", complete: { (QNResponseInfo, String, resp) -> Void in
            
            }, option: nil)
    }

**Comment by longbai** [comment]
@Kivenhaoyu :+1:

**Comment by xspyhack** [comment]
Oh my boys, Of course I knew how to use Objective-C in Swift projects. But it does not work.

**Comment by xspyhack** [comment]
I can use AFNetworking which is pod with 'Qiniu ~> 1.7'. But there is an error in QiniuSDK in file QNStats.h and others files which imported AFNetworking.

**Comment by longbai** [comment]
Could you give me the sdk version? The latest version has fixed the isssue. Could you give me the demo project, thanks.

**Comment by xspyhack** [comment]
Sure, it is the version 7.0.14 that I pod yesterday. You should not import AFNetworking Framework like this but use Cocoapods to import. --By: Kevin

**Comment by xspyhack** [comment]
I think it had fixed in 7.0.15

**Comment by Kivenhaoyu** [comment]
what is your pods version? The latest version is 7.0.15
