### ISSUE TITLE
请增加对Share extension的支持。

### ISSUE THREAD

**Issue by iBenjamin** [qiniu/objc-sdk#104]
根据http://stackoverflow.com/questions/26172783/upload-nsurlsesssion-becomes-invalidated-in-sharing-extension-in-ios8-with-error
中描述。如果不添加sharedContainerIdentifier会报995错误。

**Comment by longbai** [comment]
收到，今晚加上

**Comment by longbai** [comment]
#106

**Comment by longbai** [comment]
参考了 这几个，后台上传目前还不行，所以去掉。http://stackoverflow.com/questions/25660363/upload-tasks-from-nsdata-are-not-supported-in-background-sessions 
http://stackoverflow.com/questions/27154006/how-to-upload-task-in-background-using-afnetworking
http://openstackwiki.org/wiki/Wie_zum_Hochladen_von_Aufgabe_im_Hintergrund_unter_Verwendung_von_Afnetworking
