### ISSUE TITLE
pod不能安装7.0.16版本

### ISSUE THREAD

**Issue by jasonwwang** [qiniu/objc-sdk#109]
如题。为什么我这里显示 pod 上最高的SDK版本是 7.0.15呢？

-> Qiniu (7.0.15)
   Qiniu Resource Storage SDK for iOS and Mac
   pod 'Qiniu', '~> 7.0.15'
   - Homepage: https://github.com/qiniu/objc-sdk
   - Source:   https://github.com/qiniu/objc-sdk.git
   - Versions: 7.0.15, 7.0.14, 7.0.13, 7.0.12, 7.0.11.1, 7.0.11, 7.0.10,
   7.0.9.1, 7.0.8, 7.0.7, 7.0.6, 7.0.5, 7.0.4, 7.0.3, 7.0.2, 7.0.1, 7.0.0,
   6.3.3.1, 6.3.2, 6.3.1, 6.2.2 [master repo]

**Comment by longbai** [comment]
http://cocoadocs.org/docsets/Qiniu/7.0.16/ 
这里有啊，是否运行了pod update ?

**Comment by jasonwwang** [comment]
一直是手动修改版本号，然后 pod install 来管理。update 没试，我试试哈。
不过 pod search qiniu 确实显示最新版本到 7.0.15

**Comment by jasonwwang** [comment]
直接执行pod update会因为QIANG的问题不成功，所以执行的是 pod update --verbose --no-repo-update。结果仍然是 7.0.15。和 udpate 后面的参数有关系吗？

**Comment by jasonwwang** [comment]
直接 pod update 后成功了。
