### ISSUE TITLE
上传文件403错误

### ISSUE THREAD

**Issue by ceoacai** [qiniu/objc-sdk#115]
QNResponseInfo.error

Error Domain=qiniu.com Code=403 "(null)" UserInfo={error=key doesn't match with scope}

**Comment by longbai** [comment]
这个是token不对，token的key要和上传一致

**Comment by ceoacai** [comment]
@longbai  QNUploadManager.putData(NSData, key: nil, token: uptoken, complete)
你是说这个key要和生成的uptoken的key一致吗，我是在上传的时候出现错误

**Comment by longbai** [comment]
是的 @ceoacai

**Comment by ceoacai** [comment]
@longbai 谢谢
