### ISSUE TITLE
AFNetworking-3.x 分支编译不通过

### ISSUE THREAD

**Issue by skyline75489** [qiniu/objc-sdk#116]
https://github.com/qiniu/objc-sdk/blob/AFNetworking-3.x/QiniuSDK%2FHttp%2FQNStats.m#L256

报错：

    Sending 'NSProgress *__strong *' to parameter of incompatible type 'void (^ _Nullable)(NSProgress * _Nonnull __strong)'

环境：Xcode 7.2

**Comment by q2564063** [comment]
同样问题，求解答

**Comment by shuaiyinoo** [comment]
我也是 用的AFNetworking 3.x的版本 怎么使用 求帮助

**Comment by skyline75489** [comment]
除了这个问题之外，能不能给 AFNetworking-3.0 分支单独搞一个 pod 之类的，用 git 仓库安装的话，不能保证版本的稳定

**Comment by shuaiyinoo** [comment]
我发现了IOS 简单的上传数据根本不需要用到官方提供的框架，我自己尝试了一下 果然获得了成功，现在我把代码贴到下面，供大家参考注意用的是AFNetworking  3.x的框架

方法
+ (void)postQN:(NSString *)url params:(id)params data:(NSData *)data fileName:(NSString *)key mimeType:(NSString *)mime success:(void (^)(id json))success failure:(void (^)(NSError *error))failure{
    
    NSString * urlStr = url;
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    //manager.responseSerializer.acceptableContentTypes = [manager.responseSerializer.acceptableContentTypes setByAddingObject:@"multipart/form-data"];
    manager.securityPolicy.allowInvalidCertificates = YES;//允许没有加密请求
    
    [manager POST:urlStr parameters:params
        constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
            //
            [formData appendPartWithFileData:data name:@"file" fileName:key mimeType:mime];
            
        } progress:^(NSProgress * _Nonnull uploadProgress) {
            //
    
        } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
            //返回的正文数据
            success(responseObject);
    
        } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
            
            failure(error);
    
        }];
}

调用
                                                          //第二步 用七牛API提交用户图片
                                                          [XBHttpTool postQN:@"http://upload.qiniu.com/" params:@{@"token":token,@"key":avatarImageSrc}
                                                                        data:qiniuAvatarImage
                                                                    fileName:avatarImageSrc
                                                                    mimeType:@"application/octet-stream"
                                                                     success:^(id json) {
                                                                         
                                                                         //第三步 提交用户信息
                                                                     }
                                                                     failure:^(NSError *error) {
                                                                         NSLog(@"%@", error);
                                                                     }];

**Comment by q2564063** [comment]
把那个   &progress  改为   ^(NSProgress *progress){       /*回掉的block*/      };

**Comment by longbai** [comment]
我们这边看下，暂时不方便给AFN 3 增加一个版本，后面 我们看情况 直接用NSUrlxxx 写好了，版本分裂太多，比较难控制。@shuaiyinoo :+1:

**Comment by shuaiyinoo** [comment]
@longbai 这么晚还在看 提问

**Comment by skyline75489** [comment]
@longbai  可不可以搞成 AFNetworking 那种分 subspec 的？感觉也是可以的

**Comment by longbai** [comment]
fixed #118

**Comment by ruanstao** [comment]
[_httpManager uploadTaskWithRequest:request fromData:nil progress:&progress completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) 


AFN 3.0正式版中，关于进度的回调是用Block，接口有变，七牛能不能更新下接口

**Comment by longbai** [comment]
已经修正
