### ISSUE TITLE
请把QNStats.count类型设成NSUInteger

### ISSUE THREAD

**Issue by maimake** [qiniu/objc-sdk#119]
因为你们这个QNStats.count类型定了int，导致很多其他第三方库有使用@selector(count)的都报错了！！！

错误原因：multiple methods named `count` found with mismatched result
```objc
id arr = @[];    
[arr performSelector:@selector(count)];
```

请把改一下类型为`@property NSUInteger count;`

**Comment by longbai** [comment]
好的，我们看下

**Comment by longbai** [comment]
fixed in #120
