### ISSUE TITLE
upload failed

### ISSUE THREAD

**Issue by CharsDavy** [qiniu/objc-sdk#121]
使用https://acc.qbox.me/oauth2/token这个链接通过网络获取token，网络返回获取token成功，但上载文件失败。请问是否是因为少了一个步骤而不能唯一定位账号中的空间所导致，请问该如何解决这个问题？谢谢

**Comment by longbai** [comment]
汗，这个token 不能用来上传，建议参考 文档 http://developer.qiniu.com/docs/v6/api/reference/security/put-policy.html

**Comment by CharsDavy** [comment]
好的，谢谢。
另外，如果我是使用“空间名+AccessKey+SecretKey”通过服务端代码生成的token，是否这个token也是只有30天有效期呢？

**Comment by longbai** [comment]
这个有效期 可以自己指定，1000年都行

**Comment by CharsDavy** [comment]
谢谢
