### ISSUE TITLE
pod安装出来是Qiniu 7.0.16+AFNetworking 2.6.3

### ISSUE THREAD

**Issue by SummertimSadness** [qiniu/objc-sdk#126]
不是应该支持AFNetworking 3.0以上吗？
platform :ios, '7.0'
target 'QiNiuDemo' do
pod 'AFNetworking'
pod 'Qiniu'
end

安装成功后显示

ownloading dependencies
Installing AFNetworking 2.6.3 (was 3.0.4)
Installing HappyDNS (0.2.3)
Installing Qiniu 7.0.16 (was 6.3.3.1)
Generating Pods project
Integrating client project
Sending stats

**Comment by longbai** [comment]
3.0 是 有 专门的分支

**Comment by SummertimSadness** [comment]
那pod安装的时候我应该怎么做？

**Comment by SummertimSadness** [comment]
希望贵公司能够自己做网络请求，以免和项目的网络请求框架冲突。只是一个图片上传，没必要添加整个第三方网络请求框架吧

**Comment by SummertimSadness** [comment]
比如说AFNetworking有一个BUG影响了我的项目，现在AFNetworking更新修复了，更换了方法调用，但是你们的代码没有更新，导致我这边也更新不到修复过的AFNetworking

**Comment by longbai** [comment]
@SummertimSadness 后面会的， pod 指定 分支为 3.0, 不要用版本 
`pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'`

**Comment by SummertimSadness** [comment]
所以强烈建议去掉AFNetworking的依赖

**Comment by RuofeiLv** [comment]
这种做法太业余了 现在这个问题还没有解决 无语...
[!] Unable to satisfy the following requirements:

- `AFNetworking (~> 3.0)` required by `Podfile`
- `AFNetworking (= 3.1.0)` required by `Podfile.lock`
- `AFNetworking (~> 3.0.0-beta.2)` required by `Qiniu (7.0.16)`

**Comment by longbai** [comment]
@RuofeiLv 建议使用3.0 的分支

**Comment by SummertimSadness** [comment]
公司因为你们使用了AF，所以拒绝升级到最新的SDK了，希望尽早解决第三方库的依赖

**Comment by longbai** [comment]
pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'

我尽快去掉AFNetworking的依赖吧
