### ISSUE TITLE
关于NSURLSession后台上传的问题

### ISSUE THREAD

**Issue by lucifer001** [qiniu/objc-sdk#132]
SDK中上传所使用的AFNetworking接口
![Uploading fromData.jpeg…]()
采用data形式上传
此方式上传就没法实现后台上传

需要采用 路径的方式上传
![Uploading fromFile.jpeg…]()

请问现在的方案中是否有关于后台上传的解决方案呢？
望指教~

**Comment by lucifer001** [comment]
![Uploading fromFile.jpeg…]()

**Comment by lucifer001** [comment]
![Uploading fromFile.jpeg…]()

**Comment by longbai** [comment]
后台上传暂时不考虑，因为无法进行分片，而且后续信息也无法同步。
