### ISSUE TITLE
显示进度问题依然没有解决

### ISSUE THREAD

**Issue by MonkeyHZT** [qiniu/objc-sdk#135]
仍然为95.0时卡顿并且传递的进度值一直未95.0.直到突然完成.并且网络监测类QNReachability与其他开源项目Reachability中NetworkReachable,NetworkUnreachable 重名

**Comment by longbai** [comment]
重名的我们再看下，95.0 是上行数据流完成，等待服务器返回。

**Comment by MonkeyHZT** [comment]
同时使用新增的QNUploadManager中的putALAsset:key:token:complete:option 方法在4s  8.1.3的系统下内存会暴涨.感觉读出来的data数据没有释放的感觉.7.0.3 mini2 与 9.3.1  iPhone6系统上不存在这个问题

**Comment by longbai** [comment]
@MonkeyHZT 我们看下

**Comment by MonkeyHZT** [comment]
收到.十分感谢

**Comment by Kivenhaoyu** [comment]
@MonkeyHZT 方便把你的内存暴涨的数据截图一下吗？

**Comment by ChinaChailu** [comment]
请尽快解决 上传进度不准确的问题 先返回的是 大的数字 0.95 然后又从0.1开始返回

**Comment by longbai** [comment]
#145 fixed
