### ISSUE TITLE
你们的SDK什么时候跟进一下最新的AFNetworking版本

### ISSUE THREAD

**Issue by ufosky** [qiniu/objc-sdk#136]
我才发现我的应用一直没有更新AFNetworking是因为你们SDK依赖导致的，好不容易找个3.x（ https://github.com/qiniu/objc-sdk/tree/AFNetworking-3.x ）的分支竟然还是依赖beta版本  https://github.com/qiniu/objc-sdk/blob/AFNetworking-3.x/Qiniu.podspec

**Comment by ufosky** [comment]
或者还是直接贴一段示例代码怎么用，自己写上传的代码好了，你们这个sdk依赖让人都没法用到别人最新的库了

**Comment by longbai** [comment]
我们改下

**Comment by longbai** [comment]
已经改成依赖主版本了，@ufosky  抱歉给您带来了麻烦
