### ISSUE TITLE
7.0的sdk只能使用2.6.3的AFNetWorking

### ISSUE THREAD

**Issue by zhkufish** [qiniu/objc-sdk#147]

**Comment by zhkufish** [comment]
- `AFNetworking (> 3.0)` required by `Podfile`
- `AFNetworking (~> 2.0)` required by `Qiniu (7.0.0)`

**Comment by longbai** [comment]
麻烦用下这个分支，https://github.com/qiniu/objc-sdk/tree/AFNetworking-3.x
