### ISSUE TITLE
7.x / AFNetworking-3.x是否已经去除ipv6不兼容代码？

### ISSUE THREAD

**Issue by jimple** [qiniu/objc-sdk#150]
你好，
7.x / AFNetworking-3.x 更新下来的版本是 7.0.16。是不是6月1号前还要更新一次？
Installing Qiniu (7.0.16)

谢谢！

**Comment by longbai** [comment]
好的，我们处理下

**Comment by 1454449201** [comment]
你好,最新的去除ipv6不兼容代码的版本在 pod上更新了吗?用7.x / AFNetworking-3.x是否是已经更新过的呢?

**Comment by longbai** [comment]
#152 3.x已经处理。 主分支上也处理了。
