### ISSUE TITLE
请问这个问题怎么解决

### ISSUE THREAD

**Issue by 542604974** [qiniu/objc-sdk#153]
[!] Unable to satisfy the following requirements:

- `AFNetworking (~> 3.0)` required by `Podfile`
- `AFNetworking (~> 2.0)` required by `Qiniu (7.0.0)`

**Comment by Kivenhaoyu** [comment]
pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'

**Comment by longbai** [comment]
fixed #154
