### ISSUE TITLE
目前QiniuSDK 7.0.18 好像不支持IPv6

### ISSUE THREAD

**Issue by suxinde2009** [qiniu/objc-sdk#157]
hi，目前的QiniuSDK 7.0.18好像不支持IPv6，请问七牛官方近期是否有考虑支持IPv6？

**Comment by longbai** [comment]
sdk层面已经去掉了ipv4 相关代码。但服务器只有ipv4 地址。

**Comment by zzyspace** [comment]
也就是说, 代码上已经去掉了IPv4相关代码了, 但是iPv6-Only的环境下依旧是没办法完成上传的, 因为是写死ipv4地址的是吗? 那么这样的话会影响审核吗? (官方的文档)[https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1]有提到**Don’t Use IP Address Literals**

**Comment by longbai** [comment]
前几天iOS8 有些问题，对这个兼容性不好，现在7.0.19.1 已经处理了。IP 是作为上传失败的备选，而不是直接使用。官方是不建议，但也给出了要用IP的方案。

**Comment by zzyspace** [comment]
谢谢答复, 等待7.0.19的release

**Comment by zzyspace** [comment]
7.0.19.1不支持AFNetwoking 3.x吗? 里面还用到AFHTTPRequestOperation等类. 请问如何解决

**Comment by longbai** [comment]
@zzyspace AFN3 有 另外的3.x 分支，直接下载那个就可以
