### ISSUE TITLE
使用 asset 上传的时候能不能指定图片压缩？

### ISSUE THREAD

**Issue by ryzur-martin** [qiniu/objc-sdk#161]
发现通过 asset 上传是传的原图，有没有办法指定一下压缩的比率。

**Comment by suxinde2009** [comment]
可以将图片按一定压缩率导出到文件夹目录下，通过

- (void)putFile:(NSString *)filePath
                key:(NSString *)key
            token:(NSString *)token
       complete:(QNUpCompletionHandler)completionHandler
         option:(QNUploadOption *)option;

来上传
