### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by zhangpqan** [qiniu/objc-sdk#162]
Sending 'NSProgress __strong ' to parameter of incompatible type 'void (^ _Nullable)(NSProgress * _Nonnull __strong)'

progress:^(NSProgress * _Nonnull uploadProgress) {
        [delegate valueChange:uploadProgress];
    }

**Comment by longbai** [comment]
是你这个block 定义不对

**Comment by longbai** [comment]
可以参考单元测试里的写法
