### ISSUE TITLE
更新了最新SDK后, iOS8上传依旧会出现以下错误

### ISSUE THREAD

**Issue by zzyspace** [qiniu/objc-sdk#165]
po info.error
Error Domain=NSURLErrorDomain Code=-1001 "The operation couldn’t be completed. (NSURLErrorDomain error -1001.)" UserInfo=0x170866200 {NSErrorFailingURLStringKey=http://115.231.182.136:80/, NSUnderlyingError=0x170a5fa40 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1001.)", NSErrorFailingURLKey=http://115.231.182.136:80/

**Comment by longbai** [comment]
收到，我们看下，请问使用的版本是哪个，是AFN3.x的那个最新分支么？是在64 位环境下吧？

**Comment by zzyspace** [comment]
是的 3.x的最新的提交, 64位. iPhone6 8.1.2

**Comment by hupengios** [comment]
问题依旧存在，AFNetworking 3.1 Iphone6 8.4 ipv6环境下无法上传图片。期待解决问题，等待了有段时间了。

**Comment by FlyingNoob** [comment]
看了下最新提交的纪录。貌似没有做什么跟是配ipv6相关的操作，在sdk代码中。https://github.com/qiniu/objc-sdk/commit/2a7378af96aafea37a3963d9348ca8cbabe1ace4

**Comment by zzyspace** [comment]
什么时候可以更新呢, 明天就6月1号了

**Comment by longbai** [comment]
已经更新了

**Comment by zzyspace** [comment]
是哪个提交, 没找到 (不是用pod)

**Comment by longbai** [comment]
https://github.com/qiniu/objc-sdk/pull/178 刚合并的这个，不好意思，给您带来麻烦了。

**Comment by zzyspace** [comment]
谢谢, 可以了
