### ISSUE TITLE
7.x / AFNetworking-3.x

### ISSUE THREAD

**Issue by JxbSir** [qiniu/objc-sdk#169]
putData接口上传过程不会回调cancellationSignal。   master分支可以回调

**Comment by longbai** [comment]
收到，我们看下

**Comment by 1454449201** [comment]
重新更新, 出现- `HappyDNS (~> 0.3)` required by `Qiniu (7.0.20)`错误

**Comment by longbai** [comment]
fixed #182 @JxbSir

**Comment by JxbSir** [comment]
7.x / AFNetworking-3.x  Release v7.0.20 已经包含了吗？

**Comment by JxbSir** [comment]
弱弱的问下，怎么指定版本号？
pod 'Qiniu', :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'

**Comment by Kivenhaoyu** [comment]
重新更新, 出现- HappyDNS (~> 0.3) required by Qiniu (7.0.20)错误，
在终端下输入：pod setup
来更新本地的pod
如果还是不行
先删除全局的缓存：
$ sudo rm -fr ~/Library/Caches/CocoaPods/
$ sudo rm -fr ~/.cocoapods/repos/master/
还不行的话就把当前 Pods 目录清空：
$ sudo rm -fr Pods/
之后再在项目下运行：
$ pod install

**Comment by longbai** [comment]
@JxbSir 用分支的方式 不需要指定版本号，直接pod update 就行

**Comment by JxbSir** [comment]
@longbai   pod update, 其他库没有指定版本号的会被更新啊，分支方式能指定呢？

**Comment by Kivenhaoyu** [comment]
branch在cocopods不能指定版本下载，如果需要下载之前的版本可以用commit号来作为标志来下载

**Comment by JxbSir** [comment]
OK,  Thx
