### ISSUE TITLE
7.0.19.1在IPv6下上传图片超时

### ISSUE THREAD

**Issue by guibin1989** [qiniu/objc-sdk#170]
更新了最新的sdk，在IPv6下还是用不了。
附QNResponseInfo信息如下：

`<QNResponseInfo= id: A3510B1D-C38B-4109-890D-2518E24C5E34, ver: 7.0.19, status: -1001, requestId: (null), xlog: (null), xvia: (null), host: up.qiniu.com ip: (null) duration: 60.699627 s time: 1464327904 error: Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={NSUnderlyingError=0x158e42720 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=http://64:ff9b::73e7:b7a8:80/, NSErrorFailingURLKey=http://64:ff9b::73e7:b7a8:80/, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=请求超时。}>`

**Comment by hupengios** [comment]
同样的问题！

**Comment by wangjinyu** [comment]
七牛的SDK支持IPV6吗？

**Comment by wangjinyu** [comment]
按照苹果的文档改完就上传不了了

**Comment by hupengios** [comment]
iOS9系统在IPV6环境下可以上传图片


发自 网易邮箱大师
在2016年05月27日 16:31，王金宇 写道:

按照苹果的文档改完就上传不了了

**Comment by longbai** [comment]
请问是什么版本的iOS，麻烦试下最新版的SDK 看下

**Comment by guibin1989** [comment]
@longbai 更新了7.0.20之后没问题了

**Comment by LiuLongChang** [comment]
用的7.1.4 ， 返回错误信息：
<QNResponseInfo= id: 3A8E704F-7465-4BE2-A9A2-5EB7D62878CF, ver: 7.1.4, status: -1001, requestId: (null), xlog: (null), xvia: (null), host: up.qiniu.com ip: (null) duration: 61.551656 s time: 1481525939 error: Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={NSUnderlyingError=0x60000005e7e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=http://103.24.223.19:80/, NSErrorFailingURLKey=http://103.24.223.19:80/, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=请求超时。}>

**Comment by 1170197998** [comment]
超时一般是什么原因引起的
