### ISSUE TITLE
编译报错Sending 'NSProgress *__strong *' to parameter of incompatible type 'void (^ _Nullable)(NSProgress *

### ISSUE THREAD

**Issue by kinghudi** [qiniu/objc-sdk#173]
NSURLSessionUploadTask uploadTask = [_httpManager uploadTaskWithRequest:request fromData:nil progress:&progress completionHandler:^(NSURLResponse response, id responseObject, NSError *error) {
这个方法体有问题 afnetworking中progress:&progress这个不能传指针 好像没有兼容afnetworing3.0的版本啊 AFHTTPRequestOperationManager这个变量不是在3.0中都不存在了

**Comment by Kivenhaoyu** [comment]
pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
