### ISSUE TITLE
更新新版本之后- HappyDNS (~> 0.3) required by Qiniu (7.0.20)错误

### ISSUE THREAD

**Issue by 1454449201** [qiniu/objc-sdk#180]
之前好好的,用的是AF3.0.4,然后使用pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'就出现错误了

**Comment by 1454449201** [comment]
pod上没有找到HappyDNS 0.3版本的     pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'默认是七牛最新版本,默认找HappyDNS0.3,没有找到所以出错,是这样吗?

**Comment by Kivenhaoyu** [comment]
第一个方法： 项目下运行 pod setup
如果不行的话用第二个方法：
先删除全局的缓存：

$ sudo rm -fr ~/Library/Caches/CocoaPods/
$ sudo rm -fr ~/.cocoapods/repos/master/
还不行的话就把当前 Pods 目录清空：

$ sudo rm -fr Pods/
之后再运行：

$ pod install

**Comment by Kivenhaoyu** [comment]
本地版本cocopods内的版本没有主动拉取更新，麻烦试一下上面的方法，我们这边是可以的

**Comment by ZhangCrow** [comment]
按照如上两种方式都无解

**Comment by 1454449201** [comment]
按照第一种方法,已经解决了.谢谢
