### ISSUE TITLE
请问下什么时候可以支持https上传

### ISSUE THREAD

**Issue by santa0000** [qiniu/objc-sdk#185]
据说明年苹果会禁用http

**Comment by longbai** [comment]
可以支持，将上传地址替换为https://up.qbox.me

**Comment by santa0000** [comment]
问题是我是调用你们sdk的，你们sdk很多地方写死了用http
建议还是你们sdk提供接口来控制用http还是https把

**Comment by longbai** [comment]
没有写死，有接口的，通过设置zone 就可以，我让同事给个实例代码给你

**Comment by santa0000** [comment]
设置哪里？看了下disableATS，好像没有作用啊

**Comment by Kivenhaoyu** [comment]
[https://github.com/qiniudemo/qiniu-lab-iOS](https://github.com/qiniudemo/qiniu-lab-iOS)
Demo例子，其中有一个https上传，可以看一下

**Comment by longbai** [comment]
https://github.com/qiniudemo/qiniu-lab-iOS/blob/eb35de2778ece9a7a0b2fae31d9434177ee3ec6e/QNAaronTest/QNAaronTest/SecondVC/QN_UploadHttps.m#L129

**Comment by jiejunping** [comment]
android的sdk 上传地址也要换https，  怎么做。接口设置吗？

**Comment by longbai** [comment]
@jiejunping 同样的方式，将 zone里面的上传地址换一下 就成

**Comment by jiejunping** [comment]
@longbai  我用的是compile 'com.qiniu:qiniu-android-sdk:7.2.+'  这种接入方式。没法手动修改zone的上传地址。

**Comment by rain1458** [comment]
@longbai 请问获取和下载以前上传过的图片,  有没有提供https接口呢?

**Comment by longbai** [comment]
@Zhulmin 这个要自己进行处理，下载功能有https 的
