### ISSUE TITLE
Swift的坑可以开了吧

### ISSUE THREAD

**Issue by NSObjects** [qiniu/objc-sdk#186]

**Comment by devSC** [comment]
同问.

**Comment by longbai** [comment]
在开，加油中

**Comment by devSC** [comment]
大概啥时间可以发布呢?

**Comment by peaceful321** [comment]
这个具体要看开发的项目计划；具体时间还不是很清楚.......

**Comment by henry95** [comment]
swift的还不出来吗。。。。

**Comment by nzmax** [comment]
对。。。都19年了要

**Comment by NSObjects** [comment]
算了算了， 我转行写GO去了。。

**Comment by gee1k** [comment]
19 年了，有Swift版了吗

**Comment by liuzhuoming** [comment]
> 在开，加油中

9102年了，好了么，实在不行先去掉AFNetWorking的依赖啊

**Comment by gee1k** [comment]
@liuzhuoming 自己写吧，我已经自己写了  

https://github.com/gee1k/uPic

**Comment by YangSen-qn** [comment]
现在iOS OC 和 Swift混编效果也是可以的，现在最新版本对AF的依赖已经去除。 @liuzhuoming
