### ISSUE TITLE
什么时候去掉AF的依赖啊？

### ISSUE THREAD

**Issue by YasinZhou** [qiniu/objc-sdk#189]

**Comment by YasinZhou** [comment]
马上都半年了，什么时候能去掉依赖啊？

**Comment by peaceful321** [comment]
你好，请问需要去掉的目的或者需求是什么?
可否详细说明一下；

**Comment by YasinZhou** [comment]
之前就说过了，你们的AF更新可能会不及时，无法保证和官方的同步，而且你们的上传功能那么简单，何必去依赖AF呢，自己写一套不是更合适？

**Comment by jemygraw** [comment]
目前我们会保证和AF的官方同步。所以不用担心了。

**Comment by YasinZhou** [comment]
我觉得你们这样有点自私，AF是使用最多的开源库，作为第三方库应该尽量避免引用AF，否则我们的应用就要根据你们来进行AF版本的控制。重写了你们的部分代码，已经自己去掉依赖了
