### ISSUE TITLE
上传失败，提示域名解析错误

### ISSUE THREAD

**Issue by codingoc** [qiniu/objc-sdk#190]
App长时间处于后台，再次唤醒进行上传时，提示域名解析错误，无法上传，iOS 9.3.2

**Comment by longbai** [comment]
收到，我们看下

**Comment by longbai** [comment]
sdk 版本多少？

**Comment by Kivenhaoyu** [comment]
代码能截个图，顺便描述一下你具体的操作吗？我们这边看一下

**Comment by Kivenhaoyu** [comment]
或者直接加我的qq：1132628199，麻烦注明issue号码

**Comment by 2014Roy** [comment]
挂美国VPN，提示上传失败<QNResponseInfo= id: 94C3CBA4-A5A8-4D6C-8752-1700277A9832, ver: 7.0.19, status: 579, requestId: VWAAAMFuVK1FM2AU, xlog: s.ph;s.put.tw;s.put.tr;s.put.tw;s.put.tr;s.ph;PFDS;PFDS:1;rs21_3.sel/not found;rs20_3.sel/not found;rdb.g/no such key;DBD/404;v4.get/Document not found;rs21_3.ins;qtbl.ins:2;mc.s;RS:3;rs.put:4;rs-upload.putFile:6;QINIUPROXY:93/502;UP.CB:94;up:/upload callback failed;UP:303/579, xvia: (null), host: upload.qiniu.com ip: 103.24.223.18 duration: 11.480396 s time: 1468229853 error: Error Domain=qiniu.com Code=579 "(null)" UserInfo={error={"callback_url":"http://webapi.gagahi.com:8080/GAGA/V4.0/File/UploadCallback","callback_bodyType":"application/x-www-form-urlencoded","callback_body":"bucket=gaga4\u0026gagaId=a442577496b94d209486429d9c16e583\u0026no=1\u0026fileType=AV\u0026key=a838aa748a1d45508d7819b0f95e4515\u0026groupNo=null","token":"","err_code":502,"error":"Post http://webapi.gagahi.com:8080/GAGA/V4.0/File/UploadCallback: dial tcp 114.55.102.161:8080: no route to host","hash":"FhIkbRYBN_H8IDvpr9ZN_NeXLs8r","key":"a838aa748a1d45508d7819b0f95e4515"}}>

Why ?

**Comment by 2014Roy** [comment]
<QNResponseInfo= id: 94C3CBA4-A5A8-4D6C-8752-1700277A9832, ver: 7.0.19, status: 579, requestId: VWAAAMFuVK1FM2AU, xlog: s.ph;s.put.tw;s.put.tr;s.put.tw;s.put.tr;s.ph;PFDS;PFDS:1;rs21_3.sel/not found;rs20_3.sel/not found;rdb.g/no such key;DBD/404;v4.get/Document not found;rs21_3.ins;qtbl.ins:2;mc.s;RS:3;rs.put:4;rs-upload.putFile:6;QINIUPROXY:93/502;UP.CB:94;up:/upload callback failed;UP:303/579, xvia: (null), host: upload.qiniu.com ip: 103.24.223.18 duration: 11.480396 s time: 1468229853 error: Error Domain=qiniu.com Code=579 "(null)" UserInfo={error={"callback_url":"http://webapi.gagahi.com:8080/GAGA/V4.0/File/UploadCallback","callback_bodyType":"application/x-www-form-urlencoded","callback_body":"bucket=gaga4\u0026gagaId=a442577496b94d209486429d9c16e583\u0026no=1\u0026fileType=AV\u0026key=a838aa748a1d45508d7819b0f95e4515\u0026groupNo=null","token":"","err_code":502,"error":"Post http://webapi.gagahi.com:8080/GAGA/V4.0/File/UploadCallback: dial tcp 114.55.102.161:8080: no route to host","hash":"FhIkbRYBN_H8IDvpr9ZN_NeXLs8r","key":"a838aa748a1d45508d7819b0f95e4515"}}>

**Comment by peaceful321** [comment]
579    是上传成功但是回调失败。 包括业务服务器异常；七牛服务器异常；服务器间网络异常。

回调地址（callbackUrl） 必须能够在外网进行访问才行，而且七牛服务器post 了 能响应200 ok ，返回json信息；
