### ISSUE TITLE
iOS 断点续传视频的问题，求解

### ISSUE THREAD

**Issue by cumtqiangqiang** [qiniu/objc-sdk#191]
按照这样写的 实现不了是还缺少什么吗
NSError *error;
QNFileRecorder *file = [QNFileRecorder fileRecorderWithFolder:@"保存目录" error:&error];
//check error
QNUploadManager *upManager = [[QNUploadManager alloc] initWithRecorder:file];

**Comment by Kivenhaoyu** [comment]
断点续传的要求：1上传文件key一致，不得修改，2上传文件不得修改

**Comment by cumtqiangqiang** [comment]
@Kivenhaoyu     [_upManager putData:weakSelf.videoData key:weakSelf.stringKey token:weakSelf.stringToken
失败后再次上传 还用的这个方法，key video 的 data 都没变啊，还是不可以。还有我发现我在某一文件夹存储的QNFileRecorder *file，内容一直为空

**Comment by Kivenhaoyu** [comment]
https://github.com/qiniudemo/qiniu-lab-iOS可以看一下这个，里面有断点续传的业务demo

**Comment by peaceful321** [comment]
建议可以提供单，找七牛的技术支持，有ios sdk 同事回复的；
