### ISSUE TITLE
上传一个视频文件 50%的时候想取消本次上传怎么办

### ISSUE THREAD

**Issue by LL1992** [qiniu/objc-sdk#193]
上传一个视频文件 50%的时候想取消本次上传怎么办。
另：有没有上传视频的demo 
感谢

**Comment by longbai** [comment]
有cancel 函数

**Comment by gratefulHeart** [comment]
cancel函数 调用后是不是还会持续一会儿才会取消

**Comment by jemygraw** [comment]
@gratefulHeart 嗯，会处理完当前的请求然后结束。
