### ISSUE TITLE
用了七牛SDK上传结束后内存占用严重

### ISSUE THREAD

**Issue by dungeonsnd** [qiniu/objc-sdk#195]
我用qiniu ios sdk上传约50M的视频文件，上传前我的APP内存占用不到10M，上传开始后内存占用约60-70M，而**上传结束很久了内存依然没有降下来。请问什么原因？**    而且我觉得超过阀值时不应该把文件全部读到内存中啊，比如一个视频文件400M，我断点上传时SDK显然不应该一次性全部读到内存中吧。

另外，**顺便问一下上传有没有暂停上传的API** ？比如用户切换到3G网络时APP弹出ALERT，用户确认之前我想把上传任务暂停，用户确认前即不取消正在上传的任务 也不消耗用户的3G流量。cancellationSignalBlock 不知道能否满足我的要求，这个BLOCK是取消还是暂停？ 即假如上传了100KB，取消之后就白传了？

我使用的是下面的方法，

```
    NSError *error = nil;
    NSString * dir = [NSTemporaryDirectory() stringByAppendingString:@"qiniutest"];
    QNFileRecorder *filerec = [QNFileRecorder fileRecorderWithFolder:dir
                                                               error:&error];
    if (error) {
        DDLogWarn(@"recorder error %@", error);
    }
    QNUploadManager *upManager = [[QNUploadManager alloc] initWithRecorder:filerec];

    QNUpCancellationSignal cancellationSignalBlock =^BOOL(){
        AFNetworkReachabilityStatus status =[HttpNetwork networkStatus];
        if (status==AFNetworkReachabilityStatusReachableViaWiFi) {
            return NO;
        } else if (status!=AFNetworkReachabilityStatusNotReachable) {
            return YES;
        } else {
            return [self networkChangedMsgBox];
        }
    };

    QNUploadOption *opt = [[QNUploadOption alloc] initWithMime:@"application/octet-stream"  // @"text/plain"
                                               progressHandler:^(NSString *key, float percent){
                                                   DDLogVerbose(@"key=%@, percent=%.3f", key, percent);
                                               }
                                                        params:@{ @"x:test":@"fooval" }
                                                      checkCrc:YES
                                            cancellationSignal:cancellationSignalBlock ];

    [upManager putFile:file
                   key:key
                 token:token
              complete: ^(QNResponseInfo *info, NSString *key, NSDictionary *resp) {
                  DDLogVerbose(@"%@", info);
                  DDLogVerbose(@"%@", resp);
                  if (succ) {
                      succ(file);
                  }
              }
                option:opt];

```

**Comment by longbai** [comment]
断点续上传 一次只读一部分，读完 会释放。

**Comment by dungeonsnd** [comment]
你好，我测试发现上传完了内存确实没有释放。请问问题出在哪？

我把 [upManager putFile  这个调用注释掉后，内存不会增长。
到底是我用的问题， 还是这个SDK内部内存管理有问题。 你需要复现的 demo吗？ 我可以新建一个复现 demo 发给你，但是基本上就是我上面贴出来的代码。

其他人有遇到过吗?  上传50M的文件试试看呢，1、2MB的文件你们可能看不出来。

谢谢~

**Comment by Kivenhaoyu** [comment]
你好，可以发一下demo过来看一下

**Comment by Kivenhaoyu** [comment]
1132628199我的qq

**Comment by dungeonsnd** [comment]
你好，加QQ好友请求已发。
另外，复现demo已经上传到我的一个测试仓库，地址如下，
https://github.com/dungeonsnd/test-code/tree/master/lite_test/TestQiniuUploadMem

下面是demo运行后的截图，

上传前:
<img width="381" alt="87795ee7-15c1-4a98-9085-f1cf4a344f75" src="https://cloud.githubusercontent.com/assets/4064581/18228920/c2543812-7294-11e6-994b-4e522c5f02ff.png">

上传中:
<img width="963" alt="bd1ebfe7-6c1f-4dda-8785-b340e76cdf5f" src="https://cloud.githubusercontent.com/assets/4064581/18228921/c5dfacbe-7294-11e6-992d-3751bc4ee972.png">


上传结束，一段时间后：
<img width="870" alt="9eb2888c-c41a-43b0-9e51-58dc471e8073" src="https://cloud.githubusercontent.com/assets/4064581/18228923/cf313eae-7294-11e6-8381-13c1cef021f1.png">

成功后，在网页上看到上传的文件:
<img width="935" alt="eb9ad01e-ad84-40f0-9d4b-c10b4c96581a" src="https://cloud.githubusercontent.com/assets/4064581/18228926/d731c826-7294-11e6-913c-d66e8f511183.png">

**Comment by dungeonsnd** [comment]
下面是用#  **_iphone5s, iOS 9.0.3_** 来测试，结果如下，

开始上传前：

上传中:


下传结束后：

**Comment by dungeonsnd** [comment]
下面是用#  **_iphone5s, iOS 9.0.3_** 来测试，结果如下，

开始上传前：
![image](https://cloud.githubusercontent.com/assets/4064581/18239502/4ff3cf32-7378-11e6-860d-598b1f3b4eab.png)


上传中:
![image](https://cloud.githubusercontent.com/assets/4064581/18239509/55ac64d4-7378-11e6-8efb-3ebe842672ed.png)



下传结束后：
![image](https://cloud.githubusercontent.com/assets/4064581/18239515/5d1c380c-7378-11e6-9bf1-d12ec8e1a587.png)

**Comment by dungeonsnd** [comment]
下面是用# iphone 6, iOS 8.0.2 来测试，结果如下，

开始上传前：
![image](https://cloud.githubusercontent.com/assets/4064581/18239547/8558f4f4-7378-11e6-9d2e-2aa571b2a0e9.png)


上传中:
![image](https://cloud.githubusercontent.com/assets/4064581/18239553/8f6ce9a0-7378-11e6-962d-64b359aa1524.png)


下传结束后：
![image](https://cloud.githubusercontent.com/assets/4064581/18239556/94b11c9c-7378-11e6-9d8a-bfad438ab1b6.png)

**Comment by dungeonsnd** [comment]
下面是用# iphone 4s, iOS 9.2.0 来测试，结果如下，

开始上传前：
![image](https://cloud.githubusercontent.com/assets/4064581/18239582/bd4d37a8-7378-11e6-9386-430bd7b961c5.png)


上传中:
![image](https://cloud.githubusercontent.com/assets/4064581/18239586/c2682d38-7378-11e6-96df-c0a48cb9e62d.png)

![image](https://cloud.githubusercontent.com/assets/4064581/18239587/c92fad58-7378-11e6-8b9e-a55a9359efb3.png)


下传结束后：
![image](https://cloud.githubusercontent.com/assets/4064581/18239591/cce09886-7378-11e6-95da-a4289be24a2f.png)

**Comment by dungeonsnd** [comment]
综合我对该 SDK 的测试结果来看， 似乎该 SDK上传较大文件时，对于较高版本(比如 9.0以上)的 iOS系统内存占用及泄漏较少； 而对于较低版本的版本(如 iOS 8.x)内存占用和泄漏都比较严重。 而与设备类型应该没有太大关系，因为上述测试结果中同时有 iphone4s 9.x 和iphone4s 8.x的测试，8.x泄漏严重，而9.x泄漏较小。

暂时没时间看SDK的源码，希望有人能关注一下。

**Comment by Kivenhaoyu** [comment]
好的，我们用iOS8机器测试一下

**Comment by lehom** [comment]
确实存在这样的问题，请问解决了吗？

**Comment by lehom** [comment]
看了下sdk的源码，上传视频时，会把视频的data 全部拿出来放到QNPHAssetFile对象的引用中，这样就会造成占用大量内存（取决于视频文件的大小）。看到网上给出的解决一般是在断点续传的时候通过流式读取文件的方式。

**Comment by longbai** [comment]
@lehom https://github.com/qiniu/objc-sdk/blob/master/QiniuSDK/Common/QNFile.m#L49
这里是处理过的，而且直接调用NSData不是全部拿出来，iOS 会在内部做内存映射，不会读整个文件，只是iOS内部实现有些问题，会有缓存占用问题，后来改为大于16M就直接用fileAPI了。

**Comment by lehom** [comment]
@longbai 谢谢指教，但是确实是存在占有内存过大的问题，我用的方法是`- (void)putPHAsset:(PHAsset *)asset
               key:(NSString *)key
             token:(NSString *)token
          complete:(QNUpCompletionHandler)completionHandler
            option:(QNUploadOption *)option;`

**Comment by longbai** [comment]
@lehom PHAsset 我再看下

**Comment by Kivenhaoyu** [comment]
问题已修复，close
