### ISSUE TITLE
上传图片 错误 413

### ISSUE THREAD

**Issue by futantan** [qiniu/objc-sdk#196]
问题描述，上传图片的时候，卡在 95% 然后出错。只有有十分之一的概率能上传成功。

po responseInfo (回调第一个参数)

> QNResponseInfo= id: 6A532AC8-9BC8-480C-9EE7-6DDAB7290124, ver: 7.1.0, status: 413, requestId: eiwAADN2x3F6KWwU, eiwAADN2x3F6KWwU, xlog: UP:81/413;UP:84/413, xvia: 1.1 jswx137:0 (Cdn Cache Server V2.0), 1.1 wt88:1 (Cdn Cache Server V2.0), host: upload.qiniu.com ip: 124.161.115.34 duration: 4.866012 s time: 1471596784 error: Error Domain=qiniu.com Code=413 "(null)" UserInfo={error=exceed FsizeLimit}

回调最后一个参数为 nil

**Comment by longbai** [comment]
http://developer.qiniu.com/code/v6/api/kodo-api/up/upload.html#upload-response-status
上传图片大小超过限制，建议检查下 服务端的token 生成
