### ISSUE TITLE
设置断点续传的时候返回400

### ISSUE THREAD

**Issue by tripleCC** [qiniu/objc-sdk#199]
`status code : 400, error info : Error Domain=qiniu.com Code=400 "(null)" UserInfo={error=too many data to read, block capacity is 4194304 bytes, 4089436 byte(s) used}`

配置

QNConfiguration *configuration  = [QNConfiguration build:^(QNConfigurationBuilder *builder) {
            builder.chunkSize = 0.15 \*  1024 \* 1024;
            builder.putThreshold = 0.3 \* 1024 \* 1024;
            builder.timeoutInterval = 20;
            builder.retryMax = 2;
            builder.enableBackgroundUpload = YES;
}];

5s拍照文件，大小10M左右。  

后台设置应该最大5M。

是说chunkSize太小了，所以切割的分片过多导致too many data to read？

**Comment by longbai** [comment]
chunk 只能是256k 的整数倍
