### ISSUE TITLE
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '7.1.0.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."

### ISSUE THREAD

**Issue by cocos543** [qiniu/objc-sdk#200]
真是醉了,这SDK版本了胡乱命名..都无法上架商店了.

**Comment by longbai** [comment]
？ 这个跟SDK没什么关系吧，您可以自己改app的infolist

**Comment by cocos543** [comment]
跟SDK没关系那跟Apple有关系吗😂...苹果规定的版本号只能只3位整数分点分隔.这个SDK版本号是7.1.0.1所以被拒绝上架了.明白吗?

**Comment by betallcoffee** [comment]
@cocos543 
跟你提交的 APP 的 Info.plist 有关系。

SDK 是没有 Info.plist 文件的。

**Comment by cocos543** [comment]
我用的cocoapod安装的...里面会自动根据你的pod生成一个plist.我再强调一次,这个plist不是我工程的plist,而是cocoapod生成的.cocoapod生成的plist里面的版本号是根据你的SDK pod文件设置来的.这个问题还不明白我也没办法了.

**Comment by cocos543** [comment]
你可以在Pod的解决方案中找到Pods文件夹,里面的Qiniu=>Support Files文件夹下找到Info.plist...内容是
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>${EXECUTABLE_NAME}</string>
  <key>CFBundleIdentifier</key>
  <string>org.cocoapods.${PRODUCT_NAME:rfc****identifier}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${PRODUCT_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>FMWK</string>
  <key>CFBundleShortVersionString</key>
  <string>7.1.0.1</string>
  <key>CFBundleSignature</key>
  <string>????</string>
  <key>CFBundleVersion</key>
  <string>${CURRENT_PROJECT_VERSION}</string>
  <key>NSPrincipalClass</key>
  <string></string>
</dict>
</plist>

**Comment by longbai** [comment]
@cocos543 你可以直接改pod 里的 info.plist 。另外麻烦看下你的proj info.plist里是否有version

**Comment by cocos543** [comment]
我知道可以直接修改plist的版本号......讨论了这么久你们还没明白我的意思.总之一句话就是版本号不要弄成4段整数,你们现在的7.1.0.1这个就是不规范的,相信后面还会有人遇到这个问题.

**Comment by SPTOGUO** [comment]
我也遇到了，心累。。。。

**Comment by longbai** [comment]
... 已经更新到了 7.1.1 麻烦更新下吧
