### ISSUE TITLE
7牛上传6-10分种录制的大视频

### ISSUE THREAD

**Issue by dan15155** [qiniu/objc-sdk#201]
您好，我需要上传大视频大文件

info ===== <QNResponseInfo= id: 86604904-F97E-4891-BE94-474E4B3E3C14, ver: 7.1.0, status: -2, requestId: (null), xlog: (null), xvia: (null), host: (null) ip: (null) duration: 0.000000 s time: 1473230996 error: Error Domain=qiniu.com Code=-2 "(null)" UserInfo={error=cancelled by user}>
2016-09-07 14:49:56.909 Dingdong[839:149238] resp ===== (null)

**Comment by longbai** [comment]
没有问题，能麻烦给详细的demo 和 log 么？

**Comment by jemygraw** [comment]
这种是客户取消上传导致的。
