### ISSUE TITLE
上传的 putPHAsset 方法，如果图片在 icloud 无法上传，data 长度为 0

### ISSUE THREAD

**Issue by heqichang** [qiniu/objc-sdk#202]

**Comment by longbai** [comment]
我们看下

**Comment by Kivenhaoyu** [comment]
能具体说一下icloud的文件是下载到系统本地的吗？

**Comment by heqichang** [comment]
就是用 PHAsset.fetchAssetsWithMediaType 获取的 PHAsset，但选择的某些 asset 原图并不在本地而是在 icloud  的上的。

手机设置里开启了 icloud -> 照片 -> 优化 iPhone 存储空间 这个选项

**Comment by heqichang** [comment]
看了下你们代码，使用 requestImageDataForAsset 来获取图片数据，但是没设 isNetworkAccessAllowed = YES，这样获取到的 imageData.length = 0

**Comment by Kivenhaoyu** [comment]
目前默认是系统本地文件，才会上传，iCloud 的文件不在本地默认无资源

**Comment by heqichang** [comment]
我看着方便就直接用了，之前我也没考虑清楚，导致 app 的有些用户上传图片不成功。代码里应该注明一下。

**Comment by longbai** [comment]
@heqichang 我们处理下
