### ISSUE TITLE
QNUserAgent的clientId方法会被apple审核卡

### ISSUE THREAD

**Issue by NSKevin** [qiniu/objc-sdk#204]
苹果会认为clientId这个方法和他们的私有方法重名了，所以会认为七牛调用了私有api，然后被appStore拒绝掉。我们遇到过一次，七牛的同学能否更新一下这个方法的名称？

**Comment by longbai** [comment]
好的，我们改一下

**Comment by NSKevin** [comment]
thx  👍

**Comment by longbai** [comment]
7.1.2 已经改了，不好意思，没有及时通知

**Comment by NSKevin** [comment]
thx : )
