### ISSUE TITLE
Please update pod dependencies in .podspec

### ISSUE THREAD

**Issue by JustinFincher** [qiniu/objc-sdk#208]
As noted in [CocoaPods website](http://guides.cocoapods.org/using/the-podfile.html) : 
>'~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher  

`'HappyDNS', '~> 0.3'` will lead to HappyDNS installed with version 0.3, not 0.3.10, which lacks the typo fix (`initWithAddres`) in QNResolver, thanks. :-)

**Comment by longbai** [comment]
多谢
