### ISSUE TITLE
每次更新以后，老版本zone就不对也是醉了

### ISSUE THREAD

**Issue by passerbied** [qiniu/objc-sdk#211]
每次更新以后，老版本zone就不对也是醉了

**Comment by longbai** [comment]
请问 是 哪个 zone 不对？

**Comment by passerbied** [comment]
incorrect region, please use up-z1.qiniu.com

**Comment by longbai** [comment]
@passerbied 这个是默认的zone 和 您 使用的bucket zone 不匹配造成的，使用时 需要指明region 即 zone.

**Comment by passerbied** [comment]
请问怎么指明呢？客户端能判断出当前位置应该用哪个吗？

**Comment by longbai** [comment]
@passerbied 因为自动判断需要额外查询，在移动端 更建议 根据当前选择的bucket所在存储区去选择zone。在创建bucket 时 有进行选择哪个存储区，sdk 就根据这个选择合适的zone就好

**Comment by dylanninin** [comment]
+1 

遇到类似的问题
- bucket：在华南区
- server side: ruby-sdk 6.8.1，确实有额外的查询，uphosts 为 `up-z2.qiniu.com`，可以正常上传图片
```ruby
Query arts hosts Success: {"ttl"=>86400, "http"=>{"io"=>["http://iovip-z2.qbox.me"], "up"=>["http://up-z2.qiniu.com", "http://upload-z2.qiniu.com", "-H up-z2.qiniu.com http://183.60.214.198"]}, "https"=>{"io"=>["https://iovip-z2.qbox.me"], "up"=>["https://up-z2.qbox.me", "https://upload-z2.qbox.me"]}}
```
- iOS app: objc-sdk 7.1.5，使用 server side 生成的 uptoken 上传时出错：
```
incorrect region please use up-z2.qiniu.com
```

@longbai 建议优先使 sdk 可以正确的工作，之后再考虑如何更高效，而非为了影响影响正常使用。比如：1）在移动端优先做自动判断来选择相应的 region，即使有额外的查询；2）如有手动设置，则直接使用设置的 region 即可。

至于sdk 效率，总有办法可以改进的 ~

**Comment by GuGaobai1994** [comment]
需要修改下qiniu.js里面指定的上传的域名
https://github.com/qiniu/js-sdk/blob/master/src/qiniu.js#L158
