### ISSUE TITLE
不用cocopod可以吗，直接拖源文件的方式

### ISSUE THREAD

**Issue by shoage** [qiniu/objc-sdk#214]

**Comment by longbai** [comment]
可以，把源文件加进来，但还要把依赖的源文件 ,happydns 以及 afnetworking 加进来

**Comment by gaoqh** [comment]
除此之外还有个ag的

**Comment by peaceful321** [comment]
可以直接通过工单将问题提交给七牛的技术支持，每天都有人回复的；

**Comment by pepsin** [comment]
直接拖进来几个问题, 你们代码有些地方很不规范, 一堆警告.
二是建议你们 release 直接给个 framework 下载好了, 也省得大家编译了. 或者支持 Carthage.

![screen shot 2017-01-15 at 7 59 09 pm](https://cloud.githubusercontent.com/assets/266657/21962283/17811a9a-db5d-11e6-8317-638832a9ecae.png)

**Comment by linco1028** [comment]
我拖完QiNIUSDK 和 HappyDNS，之后在调用AFN的 uploadTaskWithRequest:progress:completionHandler:中progress 参数类型不匹配。请问是不是有跟新的SDK？

**Comment by linco1028** [comment]
我直接添加QiNIUSDK 和 HappyDNS的源文件之后，QNSessionManager中调用AFN的 uploadTaskWithRequest:progress:completionHandler:中progress 参数类型不匹配。
请问是不是有跟新的SDK？

**Comment by linco1028** [comment]
我直接添加QiNIUSDK 和 HappyDNS的源文件之后，QNSessionManager中调用AFN的 uploadTaskWithRequest:progress:completionHandler:中progress 参数类型不匹配。
请问是不是有更新的SDK？
