### ISSUE TITLE
cocoapod 安装七牛,  自动下载的依赖库跟本地冲突?

### ISSUE THREAD

**Issue by Zhulmin** [qiniu/objc-sdk#217]
cocoapod 安装七牛   pod "Qiniu", "~> 7.0.20" 

自动下载依赖库 AFNetworking (2.6.3),  跟本地冲突了怎么办?

如何指定添加依赖库版本, 如果是多个依赖库呢?

怎么设置不添加依赖库?

**Comment by rain1458** [comment]
如何指定添加依赖库版本, 如果是多个依赖库呢?

**Comment by longbai** [comment]
您可以在pod 中指定 qiniu的同时 指定 AFNetworking
