### ISSUE TITLE
ATS 安全标准的支持

### ISSUE THREAD

**Issue by zzyspace** [qiniu/objc-sdk#218]
很快就 2017 年了, 届时 Apple 会强制要求开启 ATS, 请问 SDK 中所有的网络请求都已经更新为 https 了吗? 如果没有的话, 什么时候会更新? 看了一下你们的 readme, 还停留在让用户将 Allow Arbitrary Loads 设置为 YES 的版本, Release 中也没有发现 ATS 相关的更新.

**Comment by NSKevin** [comment]
+1

**Comment by longbai** [comment]
这个直接替换就可以，没有问题的，后面我们会发一个默认https 版本

**Comment by NSKevin** [comment]
@zzyspace 这样修改 

QNConfiguration.m     line 147

+ (instancetype)zone0 {
    static QNZone *z0 = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        z0 = [QNZone createWithHost:@"upload.qbox.me" backupHost:@"up.qbox.me" ip1:@"183.136.139.16" ip2:@"183.136.139.16"];
    });
    return z0;
}

**Comment by zzyspace** [comment]
@NSKevin 谢谢! 👍

**Comment by zzyspace** [comment]
@longbai 看到你们代码里面还有使用 iPv4 的 ip 地址, 如果开启了 ATS 之后, ip 地址直接访问是不行的吧?

**Comment by sulizhan** [comment]
升级https会变贵吗

**Comment by longbai** [comment]
@zzyspace 可以的，ipv6情况下是可以访问ipv4的地址，否则在中国设备没法跑啊：）

**Comment by zzyspace** [comment]
我的意思是, ip 地址直接访问的话不能用`https`只能用`http`是吧, 因为证书是和域名绑定的, 使用`https`访问 ip 地址会导致请求失败. 那么开启 ATS 的情况下, 如果这个 ip 地址没有写到 info.plist 的话, 就会导致 ip 地址无法直接访问了, 是这样吗?

**Comment by longbai** [comment]
如果使用 https的话，就不用IP的方式了。

**Comment by zzyspace** [comment]
ok, 谢谢. 期待 https 的 release 版本

**Comment by TrueB1n** [comment]
请问默认https的版本大概什么时候更新?

**Comment by Zengzhihui** [comment]
@longbai 之前使用http的url怎么转成https的？

**Comment by dengyhgit** [comment]
@longbai   我们按照上面的改了， 但是还是偶现下面这种情况，而且频率就点高， 我们使用用户很大， 麻烦跟进下，已经很多用户反馈问题了，我不知道是不是我这按上面的改法有问题，还请你们尽快出https支持的sdk。
QNResponseInfo= id: D76F819E-3D1D-4374-AD3B-13B94FB3D754, ver: 7.1.2, status: -999, requestId: (null), xlog: (null), xvia: (null), host: upload.qiniu.com ip: (null) duration: 0.057922 s time: 1481707055 error: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://upload.qiniu.com/, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://upload.qiniu.com/}>

**Comment by peaceful321** [comment]
ios sdk 是支持https协议了的；
可以参考图片的代码：
![image](https://cloud.githubusercontent.com/assets/9206603/21216456/e683a8ba-c2e1-11e6-9236-ab68b8913d13.png)

**Comment by lgb1234a** [comment]
按照您那个修改之后，虽然可以手动访问到图片链接，但是会出现下面的警告：
![2016-12-19 11 23 14](https://cloud.githubusercontent.com/assets/12872024/21300328/f86bc446-c5dd-11e6-981b-d67a957a88d5.png)

而且客户端这边也无法加载出图片。

**Comment by WeeTom** [comment]
来催一下~尽快发布正式的支持Https的版本吧。
原来是Pods集成，现在临时改为把源码拖进去，然后按照上面的NSKevin说的改了下。

**Comment by zxy198717** [comment]
+1

**Comment by zxy198717** [comment]
七牛客服给的方案不用修改源代码:
```
NSArray *array = [[NSArray alloc] initWithObjects:@"183.136.139.16",@"183.136.139.16",nil];
    QNConfiguration *config = [QNConfiguration build:^(QNConfigurationBuilder *builder) {
        QNServiceAddress *s1 = [[QNServiceAddress alloc]init:@"https://upload.qbox.me" ips:[array objectAtIndex:0]];
        QNServiceAddress *s2 = [[QNServiceAddress alloc] init:@"https://up.qbox.me" ips:[array objectAtIndex:1]];
        builder.zone = [[QNFixedZone alloc] initWithUp:s1 upBackup:s2];
    }];

QNUploadManager *upManager = [[QNUploadManager alloc] initWithConfiguration:config];
```

**Comment by WeeTom** [comment]
这个我试过，可是我初始化用的是recorder 没有configuration这个参数 无奈…

Alvin <notifications@github.com>于2016年12月20日 周二23:32写道：

**Comment by fanweichao** [comment]
你们使用的sdk是哪个版本的?

**Comment by xx-li** [comment]
什么时候可以SDK提供ATS下https的支持？

**Comment by xupeiying** [comment]
`//        QNConfiguration *config =[QNConfiguration build:^(QNConfigurationBuilder *builder) {
//            NSMutableArray *array = [[NSMutableArray alloc] init];
//            [array addObject:[QNResolver systemResolver]];
//            
//            QNNetworkInfo *qnNetInfo = [QNNetworkInfo normal];
//            QNDnsManager *dns = [[QNDnsManager alloc] init:array networkInfo:qnNetInfo];
//            //是否选择  https  上传
//            builder.zone = [[QNAutoZone alloc] initWithHttps:YES dns:dns];
//            //设置断点续传
////            NSError *error;
////            builder.recorder =  [QNFileRecorder fileRecorderWithFolder:@"保存目录" error:&error];
//        }];
//
//       upManager = [[QNUploadManager alloc] initWithConfiguration:config];`

**Comment by xupeiying** [comment]
正式的 ATS版本的SDK什么时候发呀？？  现在改了，心里都不踏实了

**Comment by benhot** [comment]
等答案

**Comment by karosLi** [comment]
等答案

**Comment by karosLi** [comment]
NSArray *array = [[NSArray alloc] initWithObjects:@"183.136.139.16",@"183.136.139.16",nil];
    QNConfiguration *config = [QNConfiguration build:^(QNConfigurationBuilder *builder) {
        QNServiceAddress *s1 = [[QNServiceAddress alloc]init:@"https://upload.qbox.me" ips:[array objectAtIndex:0]];
        QNServiceAddress *s2 = [[QNServiceAddress alloc] init:@"https://up.qbox.me" ips:[array objectAtIndex:1]];
        builder.zone = [[QNFixedZone alloc] initWithUp:s1 upBackup:s2];
    }];

这种方式试了，并不起作用啊

**Comment by karosLi** [comment]
```

QNConfiguration *config = [QNConfiguration build:^(QNConfigurationBuilder *builder) {
            NSMutableArray *array = [[NSMutableArray alloc] init];
            [array addObject:[QNResolver systemResolver]];
            QNDnsManager *dns = [[QNDnsManager alloc] init:array networkInfo:[QNNetworkInfo normal]];
            //是否选择  https  上传
            builder.zone = [[QNAutoZone alloc] initWithHttps:YES dns:dns];//设置断点续传
        }];
```
```

2017-09-08 18:43:20.070288 xxxx[921:139025] 200 'https://up.qbox.me/' [35.9130 s]: {
    "Access-Control-Allow-Headers" = "X-File-Name, X-File-Type, X-File-Size";
    "Access-Control-Allow-Methods" = "OPTIONS, HEAD, POST";
    "Access-Control-Allow-Origin" = "*";
    "Access-Control-Expose-Headers" = "X-Log, X-Reqid";
    "Access-Control-Max-Age" = 2592000;
    "Cache-Control" = "no-store, no-cache, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 307;
    "Content-Type" = "application/json";
    Date = "Fri, 08 Sep 2017 10:42:44 GMT";
    Pragma = "no-cache";
    Server = "nginx/1.10.2";
    "X-Content-Type-Options" = nosniff;
    "X-Log" = "body:38;s.ph;s.put.tw;s.put.tr:3;s.put.tw;s.put.tr:6;s.ph;PFDS:6;PFDS:9;rs36_4.sel:4;rwro.ins:4/same entry;rs36_4.sel:5;rwro.get:5;MQ;RS.not:;RS:11;rs.put:12;rs-upload.putFile:22;BOOTS-GATE:4;DORAFOPG:5;FOPG:5;up.transform:6;QINIUPROXY:83;UP.CB:84;UP:152";
    "X-Reqid" = ZhEAAFcCFRTlXOIU;
} {
    data =     {
        "admin_id" = 1;
        "created_ip" = 0;
        "file_ext" = 1;
        "file_name" = 1;
        "file_size" = 1;
        "full_url" = "http://img.xxxx.com/2017/09/08/Fq60J1z3W6VC8-aegO_jHbS8Eu7H.jpg";
        "image_height" = 1;
        "image_width" = 1;
        "mime_type" = 0;
        time = 1504867364;
        url = "2017/09/08/Fq60J1z3W6VC8-aegO_jHbS8Eu7H.jpg";
    };
    status = 1;
}
```

结果还是 返回给我 http 的链接

**Comment by jemygraw** [comment]
@karosLi 那个返回的json是你服务端给的吧，联系那边同学换成https的吧

**Comment by wangliangliang2** [comment]
更新到最新版后。
[](https://ob9s399rs.qnssl.com/1512122172.png)
就支持https了

**Comment by bachue** [comment]
已经支持
