### ISSUE TITLE
苹果因为七牛在ip v6 崩溃被拒绝。

### ISSUE THREAD

**Issue by slowlizard** [qiniu/objc-sdk#222]
![](https://odum9helk.qnssl.com/FnUwAtFRfQ-n0A4YhIUMc73Izj-7)

定位到的错误如下：
![](https://odum9helk.qnssl.com/FuI9nTBOU9VaoM_7jD3qB1Cw7Hjy)

七牛版本：7.1.4

下面是出现的错误的代码：

![](https://odum9helk.qnssl.com/FuKm1H2k0tYb52LQfjCt_BwN8XWP)

**Comment by slowlizard** [comment]
第254行抱错

**Comment by wangliangliang2** [comment]
@slowlizard hi，是否能够提供一份能够稳定复现问题的工程，或者告诉我们如何复现，我们这边来测下。
