### ISSUE TITLE
按照官方文档集成IOS,上传二进制文件返回400

### ISSUE THREAD

**Issue by JusticeLai** [qiniu/objc-sdk#225]
NSString *token = @"服务器返回的token";
  QNUploadManager *upManager = [[QNUploadManager alloc] init];
  NSData *data = [@"Hello, World!" dataUsingEncoding : NSUTF8StringEncoding];
  [upManager putData:data key:nil token:token
            complete: ^(QNResponseInfo *info, NSString *key, NSDictionary *resp) {
              NSLog(@"info---%@", info);
              NSLog(@"resp---%@", resp);
            } option:nil];

![image](https://cloud.githubusercontent.com/assets/13083749/24443872/e43b9c00-1496-11e7-9964-7f49aeb0158b.png)

**Comment by liugang5710** [comment]
400	请求报文格式错误。
包括上传时，上传表单格式错误， key 不能为空的

**Comment by CoderQHao** [comment]
哥们 这个问题解决了吗

**Comment by jemygraw** [comment]
```
- (IBAction)uploadBytes:(UIButton *)sender {
    NSString *uploadToken=@"your upload token";
    QNUploadManager *uploadManager=[[QNUploadManager alloc]init];
    NSData *data=[@"Hello World!" dataUsingEncoding:NSUTF8StringEncoding];
    [uploadManager putData:data key:nil token:uploadToken complete:^(QNResponseInfo *info, NSString *key, NSDictionary *resp) {
        NSLog(@"info--%@",info);
        NSLog(@"resp--%@",resp);
    } option:nil];
}
```
使用这样的方式上传，暂时没有测试出错误，可以再试试看，如果有问题，请及时联系。

**Comment by liugangSwift** [comment]
已经解决了，不是代码的原因，被墙了
