### ISSUE TITLE
iOS10下demo会crash

### ISSUE THREAD

**Issue by hite** [qiniu/objc-sdk#226]
[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

麻烦改下demo配置，免去每个人都要改配置文件的麻烦

**Comment by benhot** [comment]
支持

**Comment by yiios** [comment]
手动加上就行了 

    <key>NSCameraUsageDescription</key>
    <string>cameraDesciption</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>microphoneDesciption</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>photoLibraryDesciption</string>
    <key>NSContactsUsageDescription</key>
    <string>contactsDesciption</string>

**Comment by hite** [comment]
@yiios 是的，你是对的。我的初衷是 demo工程本身加好，不需要要每个下载的人都加这个配置。我改了下我的issue描述
