### ISSUE TITLE
Invalid parameter not satisfying: URLString

### ISSUE THREAD

**Issue by chocoboxxf** [qiniu/objc-sdk#227]
上传图片时发生崩溃
设备信息：iOS 10.2.1 ，iPhone 6 Plus
堆栈信息：
0	CoreFoundation	0x000000018ab9d1b8	__exceptionPreprocess + 124 + 1245624 
1	libobjc.A.dylib	0x00000001895d455c	objc_exception_throw + 56 
2	CoreFoundation	0x000000018ab9d08c	+[NSException raise:format:] + 0 + 1245324 
3	Foundation	0x000000018b65502c	-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112 + 712748 
4	AFNetworking	0x0000000100a86768	-[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:] + 668 
5	AFNetworking	0x0000000100a86f64	-[AFHTTPRequestSerializer multipartFormRequestWithMethod:URLString:parameters:constructingBodyWithBlock:error:] + 852 
6	Qiniu	0x0000000100d25538	-[QNSessionManager multipartPost:withData:withParams:withFileName:withMimeType:withCompleteBlock:withProgressBlock:withCancelBlock:withAccess:] + 600 
7	Qiniu	0x0000000100d18918	-[QNFormUpload put] + 1392 
8	Qiniu	0x0000000100d28850	__53-[QNUploadManager putData:key:token:complete:option:]_block_invoke.88 + 48 
9	Qiniu	0x0000000100d12368	__QNAsyncRun_block_invoke + 40 
10	libdispatch.dylib	0x00000001011a5258	_dispatch_call_block_and_release + 24 
11	libdispatch.dylib	0x00000001011a5218	_dispatch_client_callout + 16 
12	libdispatch.dylib	0x00000001011b326c	_dispatch_queue_override_invoke + 980 
13	libdispatch.dylib	0x00000001011b4e2c	_dispatch_root_queue_drain + 584 
14	libdispatch.dylib	0x00000001011b4b78	_dispatch_worker_thread3 + 140 
15	libsystem_pthread.dylib	0x0000000189c2f2a0	_pthread_wqthread + 1288 
16	libsystem_pthread.dylib	0x0000000189c2ed8c	start_wqthread + 4

**Comment by Kivenhaoyu** [comment]
能否提供一下具体的操作日志，我们这边好复现一下

**Comment by jemygraw** [comment]
后续反馈问题，最好提供下源代码。
