### ISSUE TITLE
Domain=qiniu.com Code=403 "(null)"

### ISSUE THREAD

**Issue by liugangSwift** [qiniu/objc-sdk#228]
<QNResponseInfo= id: 1812E878-725F-4935-ACBF-C9E758A726FD, ver: 7.1.5, status: 403, requestId: (null), xlog: (null), xvia: (null), host: upload.qiniu.com ip: 61.162.231.199 duration: 0.269269 s time: 1494435687 error: Error Domain=qiniu.com Code=403 "(null)" UserInfo={error=<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
}>

**Comment by wangliangliang2** [comment]
请把问题描述清楚。什么情况下出现这个问题。

**Comment by jemygraw** [comment]
这个一般是由于当时的那个上传节点IP 61.162.231.199 出现故障了，导致无法上传，返回403
