### ISSUE TITLE
swift 3.1 上传的时候报错

### ISSUE THREAD

**Issue by OHeroJ** [qiniu/objc-sdk#229]
QNResponseInfo= id: 743868F7-4293-4033-9DB4-33FCD543CD24, ver: 7.1.5, status: 400, requestId: 71UAAJ9z2LSlfL0U, 71UAAJ9z2LSlfL0U, xlog: RA:122.224.95.111:80;body:2;UP:3/400;NUPROXY:159/400, xvia: (null), host: upload.qiniu.com ip: 121.15.220.4 duration: 1.220254 s time: 1494487702 error: Error Domain=qiniu.com Code=400 "(null)" UserInfo={error=incorrect region, please use up-z2.qiniu.com

**Comment by wangliangliang2** [comment]
上传空间没有对应上传token。使用最新的SDK，使用自动选择空间功能。QNAutoZone功能。

BOOL isHttps = TRUE;
QNZone * httpsZone = [[QNAutoZone alloc] initWithHttps:isHttps dns:nil];
QNConfiguration *config = [QNConfiguration build:^(QNConfigurationBuilder *builder) {
builder.zone = httpsZone;
}];

**Comment by CoderQHao** [comment]
7.1.5不是最新的吗
