### ISSUE TITLE
上传图片崩溃到这里

### ISSUE THREAD

**Issue by leftw** [qiniu/objc-sdk#231]
AFURLRequestSerialization.m 

#pragma mark - AFURLRequestSerialization

- (NSURLRequest *)requestBySerializingRequest:(NSURLRequest *)request
                               withParameters:(id)parameters
                                        error:(NSError *__autoreleasing *)error 里面

      [mutableRequest
         setHTTPBody:[NSJSONSerialization dataWithJSONObject:parameters
                                                     options:kNilOptions
                                                       error:nil]];

**Comment by Kivenhaoyu** [comment]
具体的崩溃信息麻烦提供一下
