### ISSUE TITLE
putData 应当能接受一个 fname 作为可选参数

### ISSUE THREAD

**Issue by apporc** [qiniu/objc-sdk#232]
否则魔法变量 $(fname) 为 '?'。 python 的实现中 put_data 已经支持 fname 参数。

**Comment by Kivenhaoyu** [comment]
我们目前的主要给文件命名是用的 key，所以目前没有提供 fname 的参数

**Comment by jemygraw** [comment]
可以不需要$(fname)直接用key作为fname
