### ISSUE TITLE
Error Domain=qiniu.com Code=579 "(null)"

### ISSUE THREAD

**Issue by zb1006801184** [qiniu/objc-sdk#233]
Error Domain=qiniu.com Code=579 "(null)" UserInfo={error={"callback_url":"http://test.xianhuoapp.com/Api/qiniu/callback.html","callback_bodyType":"application/x-www-form-urlencoded","callback_body":"name=%3F\u0026key=FrowTF_A2wXcubuTpLIIvO_UBQhW\u0026uid=88\u0026","token":"","err_code":502,"error":"Post http://test.xianhuoapp.com/Api/qiniu/callback.html: read tcp 115.238.138.234:55048-\u003e106.14.26.232:80: read: connection reset by peer","hash":"FrowTF_A2wXcubuTpLIIvO_UBQhW","key":"FrowTF_A2wXcubuTpLIIvO_UBQhW"}}

偶尔会出现这个错误，这是为什么。

**Comment by zb1006801184** [comment]
谁能解释一下这是为什么吗   ？出现的次数大概 50次 有一次的样子!

**Comment by jemygraw** [comment]
你的回调失败了，CallbackUrl指定的地址，响应回调失败了。
