### ISSUE TITLE
cocoapods没有搜索到 7.1版本

### ISSUE THREAD

**Issue by MrCoderDing** [qiniu/objc-sdk#235]
RT是不是我这边哪里设置不对？

**Comment by Kivenhaoyu** [comment]
先删除全局的缓存：

$ sudo rm -fr ~/Library/Caches/CocoaPods/
$ sudo rm -fr ~/.cocoapods/repos/master/
还不行的话就把当前 Pods 目录清空：

$ sudo rm -fr Pods/
之后再运行：

$ pod install
