### ISSUE TITLE
Terribly Coding!

### ISSUE THREAD

**Issue by ekingo** [qiniu/objc-sdk#236]
> NSDictionary *http = [resp objectForKey:@"http"];
    NSArray *up = [http objectForKey:@"up"];
    NSString *upHost = [up objectAtIndex:1];
    NSString *upBackup = [up objectAtIndex:0];
    NSString *ipTemp = [up objectAtIndex:2];
    NSArray *a1 = [ipTemp componentsSeparatedByString:@" "];
    NSString *ip1 = [a1 objectAtIndex:2];
    NSArray *a2 = [ip1 componentsSeparatedByString:@"//"];
    NSString *upIp = [a2 objectAtIndex:1];
    NSDictionary *https_ = [resp objectForKey:@"https"];
    NSArray *a3 = [https_ objectForKey:@"up"];
    NSString *upHttps = [a3 objectAtIndex:0];

We don't know what the response json is. if the server miss some values, it crashes!

**Comment by Kivenhaoyu** [comment]
Our server will ensure that the response json is available and complete like you see

**Comment by jemygraw** [comment]
fixed in new release 7.1.7
