### ISSUE TITLE
iOS Qiniu SDK (7.1.5) 闪退

### ISSUE THREAD

**Issue by Navimark** [qiniu/objc-sdk#237]
使用 Qiniu SDK 上传图片时候闪退。

### 出错现场

> NSInvalidArgumentException
> *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
> LiveKitSDK __26-[QNAutoZone preQuery: on:]_block_invoke (QNConfiguration.m:)
> 
> CoreFoundation	___exceptionPreprocess + 124
> libobjc.A.dylib	objc_exception_throw + 56
> CoreFoundation	-[__NSPlaceholderArray initWithObjects:count:] + 308
> CoreFoundation	+[NSArray arrayWithObjects:count:] + 52
> LiveKitSDK	__26-[QNAutoZone preQuery: on:]_block_invoke (**QNConfiguration.m:270**)
> LiveKitSDK	__54-[QNSessionManager get:withHeaders:withCompleteBlock:]_block_invoke_2 (QNSessionManager.m:326)
> LiveKitSDK	__72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 (AFURLSessionManager.m:308)
> libdispatch.dylib	__dispatch_call_block_and_release + 24
> libdispatch.dylib	__dispatch_client_callout + 16
> libdispatch.dylib	_dispatch_main_queue_callback_4CF + 444

### 调用 Qiniu 的代码
```objc
QNConfiguration *config =[QNConfiguration build:^(QNConfigurationBuilder *builder) {
                    NSMutableArray *array = [[NSMutableArray alloc] init];
                    [array addObject:[QNResolver systemResolver]];
                    QNDnsManager *dns = [[QNDnsManager alloc] init:array networkInfo:[QNNetworkInfo normal]];
                    //是否选择  https  上传
                    builder.zone = [[QNAutoZone alloc] initWithHttps:YES dns:dns];
                }];
                
QNUploadManager *uploadManager = [[QNUploadManager alloc] initWithConfiguration:config];
[uploadManager putData:imageData key:key token:token complete:completeHandler option:option];

```

###  QNConfiguration.m 的第 270 行代码
![default](https://user-images.githubusercontent.com/4392747/28348288-caf0bffc-6c6e-11e7-8fe1-b41ff490a315.png)
确实存在 info.upIp 为 nil 导致闪退的情况

截止到今天，已经发生了很多次闪退，严重影响到了 App 的整体稳定性，烦请及时修复此问题。
![image](https://user-images.githubusercontent.com/4392747/28348345-249a20e8-6c6f-11e7-9e34-e67e836638d4.png)

**Comment by jemygraw** [comment]
这个是由于当时服务端一个配置更新导致的，以修复。后续sdk会增强兼容性处理。

**Comment by jemygraw** [comment]
在新版本 7.1.7 里面不再会有这种问题存在了。
