### ISSUE TITLE
这是我用过最难用的 SDK,

### ISSUE THREAD

**Issue by liushuangddu** [qiniu/objc-sdk#240]
都是些什么人啊,一个几把 SDK 搞的这么复杂,学学人家阿里云,直接打包一个 framework 就好了,那里还要向你们这么傻逼, demo 下载下来不能运行,老子配置了半天还是不行,用最新版的 SDK,7高8搞有个变量根本不知道在哪里定义的"QNIP",demo 里面也是一样.真他妈日了狗了.

**Comment by Kivenhaoyu** [comment]
依赖库的版本全部更新一下
