### ISSUE TITLE
content-type 问题，text/html

### ISSUE THREAD

**Issue by huanglins** [qiniu/objc-sdk#242]
上传图片设置mime 为 image/jpeg，网页上显示也是 image/jpeg。但是用 AFNetworking 下载文件时，显示是 text/html，无法处理。是什么情况？

**Comment by HeraShowFeng** [comment]
用 AFNetworking 下载文件，请求若是经过你自己服务器的话，接口返回的 Content-Type类型不对，建议看下后端开发的规范是否对应
