### ISSUE TITLE
七牛内部用了AFN，但是AFN的循环引用，七牛没释放

### ISSUE THREAD

**Issue by hehe520** [qiniu/objc-sdk#243]
七牛的 QNSessionManager 内部有个 AFHTTPSessionManager *httpManager 私有属性。

创建一个 AFHTTPSessionManager 存在一个循环引用，创建多个就存在多个，然后这些循环引用释放不了，需要手动停止 AFN 的 session。

用下面这句话打破循环
AFHTTPSessionManager *mgr;
[mgr.session finishTasksAndInvalidate];

复现步骤：用 instrument 打开七牛云的Demo，然后随便上传一个文件，就会报内存泄漏了。

<img width="1045" alt="114a10a5-6e97-487d-9208-df433c700878" src="https://user-images.githubusercontent.com/8847751/28813755-41264efe-76cd-11e7-84e1-147debeaa27c.png">

![14ea86a9-45f4-40a0-b154-0d933f7c43ae](https://user-images.githubusercontent.com/8847751/28813809-6f22db56-76cd-11e7-914a-1c39f119acd0.png)

**Comment by Kivenhaoyu** [comment]
麻烦更新一下代码
