### ISSUE TITLE
怎么适配ipv6

### ISSUE THREAD

**Issue by JayLee-GitHub** [qiniu/objc-sdk#248]
集成上传图片  pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x’   在ipv6环境下上传失败，该怎么配置呢

**Comment by jemygraw** [comment]
麻烦给一些详细的bug信息，因为目前是支持ipv6的ip的

**Comment by Kivenhaoyu** [comment]
可以直接更新到 master ，目前已经是 af3.x 版本了
如果更新之后 ipv6 还是失败，麻烦给些详细的 bug

**Comment by bachue** [comment]
已经支持
