### ISSUE TITLE
There are some memory leak problem

### ISSUE THREAD

**Issue by zhichaojianer** [qiniu/objc-sdk#256]
<img width="427" alt="2017-10-20 9 53 42" src="https://user-images.githubusercontent.com/8518730/31801714-a1050692-b57c-11e7-9ce4-63ab0d134462.png">

**Comment by HeraShowFeng** [comment]
我们做过充分的测试，没有出现内存泄漏，对于图中的参数 'ret' 泄漏，其实后续是释放了，不会造成影响
