### ISSUE TITLE
连麦提示The RTC Library Not Found

### ISSUE THREAD

**Issue by aa8227869** [qiniu/objc-sdk#257]
error: Error Domain=PLRTCStreamingErrorDomain Code=-3012 "The RTC Library Not Found" UserInfo={NSLocalizedDescription=The RTC Library Not Found}

**Comment by KevinChenQiniu** [comment]
这是因为连麦用了推流的sdk，没有导入连麦的sdk，在连麦文档上下载demo使用，然后导入项目中就可以了：
https://developer.qiniu.com/pili/sdk/1639/PLMediaStreamingKit(RTC)
