### ISSUE TITLE
播放在线m3u8文件，偶尔当时经常出现黑屏或者返回上个界面还有声音

### ISSUE THREAD

**Issue by zhengchengbin610** [qiniu/objc-sdk#259]
1.因为打开使用ffmpeg播放无法seek,所以目前播放器没有使用ffmpeg，而是使用avplayer，这些问题请问有解决方案吗？七牛大神们

**Comment by jemygraw** [comment]
试试 https://github.com/pili-engineering/PLPlayerKit/
