### ISSUE TITLE
QNResponseInfo.m init 函数里如果 response body  非json格式  uInfo 为nil 需要检查处理

### ISSUE THREAD

**Issue by kaka19ace** [qiniu/objc-sdk#26]
Objc 修改仅一行: (注释)
QNResponseInfo.m
- (instancetype)init:(int)status
withReqId:(NSString *)reqId
withXLog:(NSString *)xlog
withBody:(NSData *)body {

if (self = [super init]) {
    _statusCode = status;
    _reqId = [reqId copy];
    _xlog = [xlog copy];
    if (status != 200) {
        if (body == nil) {
            _error = [[NSError alloc] initWithDomain:domain code:_statusCode userInfo:nil];
        } else {
            NSError *tmp;
            NSDictionary *uInfo = [NSJSONSerialization JSONObjectWithData:body options:NSJSONReadingMutableLeaves error:&tmp];

            /* 这段需要做 uInfo nil 判断, 否则代码执行会蹦 */
            if (tmp != nil && uInfo != nil) {
                uInfo = @{ @"error":[[NSString alloc] initWithData:body encoding:NSUTF8StringEncoding] };
            }
            _error = [[NSError alloc] initWithDomain:domain code:_statusCode userInfo:uInfo];
        }
    }
    else if (body == nil || body.length == 0) {
        NSDictionary *uInfo = @{ @"error":@"no response json" };
        _error = [[NSError alloc] initWithDomain:domain code:_statusCode userInfo:uInfo];
    }
}
return self;
}

**Comment by longbai** [comment]
@kaka19ace 多谢，我看下

**Comment by longbai** [comment]
@kaka19ace 奇怪，1 这里tmp 如果是非nil, 理论上uinfo 应该是nil; 2 如果uinfo非nil, 再次赋值应该也没影响啊。

**Comment by longbai** [comment]
是否 是没有判断 complete 回调的 ret 是否为null 造成的，500问题 有单元测试的 https://github.com/qiniu/objc-sdk/blob/master/QiniuSDKTests/QNHttpTest.m#L53

**Comment by longbai** [comment]
@kaka19ace 已经在 #27 修复，原因是字符串 非utf8 格式时 无法生成字符串。

**Comment by kaka19ace** [comment]
非常感谢
