### ISSUE TITLE
上传多个PHAsset,progressblock报错

### ISSUE THREAD

**Issue by fandongtongxue** [qiniu/objc-sdk#266]
我的解决方案目前是这样
<img width="1141" alt="wx20171205-112356 2x" src="https://user-images.githubusercontent.com/21986591/33588677-09fc1c02-d9af-11e7-994f-452247fc63d6.png">
加入block判断,防止野指针
不知道官方什么思路

**Comment by wangliangliang2** [comment]
具体的报错是什么呢？

**Comment by fandongtongxue** [comment]
<img width="2118" alt="wx20171205-124811 2x" src="https://user-images.githubusercontent.com/21986591/33590476-9cb1eef4-d9ba-11e7-9521-75a374650cd0.png">

**Comment by wangliangliang2** [comment]
根本原因不是那个问题。稍后修复。

**Comment by wangliangliang2** [comment]
已经修复。

**Comment by fandongtongxue** [comment]
更新下pod库呗

**Comment by wangliangliang2** [comment]
![image](https://user-images.githubusercontent.com/20638550/33699622-3b3251f0-db4f-11e7-84ec-82cdf425e77b.png)
更新过了，应该是你pod没更新。

**Comment by fandongtongxue** [comment]
好的,试过了,辛苦了

**Comment by longbai** [comment]
fixed in 7.2.2
