### ISSUE TITLE
升级到7.1.7，无法上传文件

### ISSUE THREAD

**Issue by hehe520** [qiniu/objc-sdk#272]
// 7.1.6 代码
QNServiceAddress *address = [[QNServiceAddress alloc] init:_url ips:nil];
QNServiceAddress *addressBackup = [[QNServiceAddress alloc] init:_backup_url ips:nil];
QNZone *zone = [[QNFixedZone alloc] initWithUp:address upBackup:addressBackup];

// 7.1.7 代码，QNServiceAddress被删掉了
QNZone *zone = [[QNFixedZone alloc] initWithupDomainList:lists];
        
1.小版本升级，怎么删了接口了
2.用 7.1.6的代码可以上传成功，用 7.1.7的代码，上传失败，其他代码一点都没改
3.QNZone中使用自定义url的文档找不到，代码注释也比较少

上传失败的 log：
TIC TCP Conn Failed [2:0x60400016a680]: 12:8 Err(-65554)
Task <CDEFEA39-D1BD-4575-AC5A-C1E868673714>.<1> HTTP load failed (error code: -1003 [12:8])

-1003 是找不到host，但是我host是有的，用7.1.6的代码是成功的，换到 7.1.7 就不行了

发现问题是，我的url是  http://www.xxxx.com，在7.1.6是正常的，但是
7.1.7 不需要 http:// 这个 schame， 只需要 www.xxxx.com，相关文档在哪里呢
我是 http:// 开头， 7.1.7 强制加了 https:// 虽然成功，但感觉有个隐患。

**Comment by YangSen-qn** [comment]
建议升级到最新版本 7.4.2，设置QNFixedZone时间URL不需要加 https, 如果使用选择 http 和 https，可以使用一下代码：
```
QNConfiguration *config = [QNConfiguration build:^(QNConfigurationBuilder *builder) {
        builder.useHttps = YES;
    }];
```

**Comment by bachue** [comment]
已经支持
