### ISSUE TITLE
上传图片报401，同一个token有时是有效的有时是没有效的

### ISSUE THREAD

**Issue by karosLi** [qiniu/objc-sdk#273]
你好，我们项目没有使用 sdk，而是直接拼的post 请求去上传的图片的。
token 是从服务器取的。但是最近经常报401，同一个token有时是有效的有时是没有效的。

能帮忙看下吗？

下面是我的请求结构体：
2018-01-11 23:06:51.845415+0800 xxx[1172:363675] POST 'https://upload.qiniu.com/': {
    "Accept-Language" = "zh-Hans-CN;q=1, en-CN;q=0.9";
    "Content-Length" = 215700;
    "Content-Type" = "multipart/form-data; boundary=Boundary+0D312F8B671F1DFA";
    "User-Agent" = "xxx/3.3.1 (iPhone; iOS 11.1; Scale/3.00)";
} 
--Boundary+CAA8FC46A3C9BA2E
Content-Disposition: form-data; name="LKDataNames[]"

imageName
--Boundary+CAA8FC46A3C9BA2E
Content-Disposition: form-data; name="LKDataTypes[]"

LKDataTypeImageJpg
--Boundary+CAA8FC46A3C9BA2E
Content-Disposition: form-data; name="LKDatas[]"
--Boundary+CAA8FC46A3C9BA2E
Content-Disposition: form-data; name="User-Agent"

Qiniu-iOS/6.3.3 (iPhone; iOS 11.1; 1515683502241913)
--Boundary+CAA8FC46A3C9BA2E
Content-Disposition: form-data; name="token"

dP5UdTA5ylgZDy4qFAGzTK_URi0EDE9UasGzWtFR:uGfv_0ef7Y2aZpFEWDVT7Cu9orU=:eyJzY29wZSI6Imxla2V5dW5kb25namlhbnNoZW4iLCJzYXZlS2V5IjoiJCh5ZWFyKVwvJChtb24pXC8kKGRheSlcLyQoZXRhZykkKGV4dCkiLCJjYWxsYmFja1VybCI6Imh0dHBzOlwvXC91c2VyLmxlb2FvLmNvbVwvYXBwXC9xaW5pdVwvY2FsbGJhY2siLCJjYWxsYmFja0JvZHkiOiJhZG1pbl9pZD0kKHg6YWRtaW5faWQpJmtleT0kKGtleSkmZm5hbWU9JChmbmFtZSkmZnNpemU9JChmc2l6ZSkmZXh0PSQoZXh0KSZtaW1lVHlwZT0kKG1pbWVUeXBlKSZ3PSQoaW1hZ2VJbmZvLndpZHRoKSZoPSQoaW1hZ2VJbmZvLmhlaWdodCkiLCJkZWFkbGluZSI6MTUxNTY5MDM3Nn0=
--Boundary+CAA8FC46A3C9BA2E
Content-Disposition: form-data; name="file"; filename="imageName_0_1515683502.242196_.jpg"
Content-Type: image/jpeg

--Boundary+CAA8FC46A3C9BA2E--

2018-01-11 23:07:01.128044+0800 xxx[1172:363675] 200 'https://upload.qiniu.com/' [4.9259 s]: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-store, no-cache, must-revalidate";
    "Content-Length" = 307;
    "Content-Type" = "application/json";
    Date = "Thu, 11 Jan 2018 15:07:01 GMT";
    Pragma = "no-cache";
    Server = "nginx/1.10.2";
    "access-control-allow-headers" = "X-File-Name, X-File-Type, X-File-Size";
    "access-control-allow-methods" = "OPTIONS, HEAD, POST";
    "access-control-expose-headers" = "X-Log, X-Reqid";
    "access-control-max-age" = 2592000;
    "x-content-type-options" = nosniff;
    "x-log" = "body;s.ph;s.put.tw;s.put.tr;s.put.tw;s.put.tr:1;s.ph;PFDS:1;PFDS:2;body;rs37_3.sel;rwro.ins/same entry;rs37_3.sel;rwro.get;MQ;RS.not:;RS;rs.put:1;rs-upload.putFile:4;BOOTS-GATE:3;DORAFOPG:4;FOPG:4;up.transform:5;QINIUPROXY:56;UP.CB:57;UP:68";
    "x-reqid" = CyIAABTI2OfbyQgV;
    "x-svr" = UP;
} {
    data =     {
        "admin_id" = 1;
        "created_ip" = 0;
        "file_ext" = 1;
        "file_name" = 1;
        "file_size" = 1;
        "full_url" = "http://img.xxx.com/2018/01/11/FpDKQnGAVsdY11DJBn30y4Koh731.jpg";
        "image_height" = 1;
        "image_width" = 1;
        "mime_type" = 0;
        time = 1515683217;
        url = "2018/01/11/FpDKQnGAVsdY11DJBn30y4Koh731.jpg";
    };
    status = 1;
}

**Comment by wanglang** [comment]
这个问题解决了么？升级sdk可否解决呢？我的是7.1.5 会出现这种情况。
