### ISSUE TITLE
http_error  上传失败 -999

### ISSUE THREAD

**Issue by MontFei** [qiniu/objc-sdk#276]
![image](https://user-images.githubusercontent.com/37868255/38089431-fc8c12c4-3391-11e8-90a4-c20d5d2df83a.png)
上传图片的时候出现-999的错误。

**Comment by jemygraw** [comment]
```
   NSURLErrorCancelled = -999,
```
根据code定义是这个错误，你可以自助排查下。
   https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Constants/index.html#//apple_ref/doc/constant_group/URL_Loading_System_Error_Codes
