### ISSUE TITLE
警告太多,希望下一个版本清理一下API的警告问题

### ISSUE THREAD

**Issue by SpringAndSummer** [qiniu/objc-sdk#277]
我用的API是Qiniu 7.2.3版本,我是一个有代码洁癖的人,有警告我一般都去处理一下,但是最新的API依然有34个警告,我大概看了一下这些警告,好多都是方法的备注问题,希望你们着手处理一下.

**Comment by jessecoding** [comment]
我用的API是Qiniu 7.24版本警告太多

**Comment by wongzigii** [comment]
![image](https://user-images.githubusercontent.com/7384288/42860564-c0a610d0-8a89-11e8-9c97-1bf8a28de7e6.png)

**Comment by wongzigii** [comment]
![image](https://user-images.githubusercontent.com/7384288/49623517-edbbf280-fa08-11e8-8128-d6479a422cca.png)

Xcode Version 10.1 (10B61)

**Comment by linbx08** [comment]
超级多的告警 怎么不优化

**Comment by Mei-Zhao** [comment]
感谢反馈，我们新版本v7.4.2发布优化了部分告警问题
