### ISSUE TITLE
pod "Qiniu", "~> 7.2" 报错，

### ISSUE THREAD

**Issue by xiaomaxiaoma** [qiniu/objc-sdk#284]
Installing HappyDNS (0.3.12)

[!] Error installing HappyDNS
[!] /usr/bin/git clone https://github.com/qiniu/happy-dns-objc.git /var/folders/k5/nrsg52v51nqf3wfxn8rs3ypm0000gn/T/d20180713-38760-gtyem5 --template= --single-branch --depth 1 --branch v0.3.12

Cloning into '/var/folders/k5/nrsg52v51nqf3wfxn8rs3ypm0000gn/T/d20180713-38760-gtyem5'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: The remote end hung up unexpectedly
fatal: protocol error: bad pack header

**Comment by jemygraw** [comment]
麻烦检查下自身的网络是否OK
