### ISSUE TITLE
sdk(7.2.5）如何设置自动判断上传空间？

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [qiniu/objc-sdk#288]
在开发者文档上：https://developer.qiniu.com/kodo/sdk/1240/objc
写着：
注意： 如使用最新版的sdk(7.1.4),可自动判断上传空间。按如下方式使用：
QNConfiguration *config =[QNConfiguration build:^(QNConfigurationBuilder *builder) {
NSMutableArray *array = [[NSMutableArray alloc] init];
[array addObject:[QNResolver systemResolver]];
QNDnsManager *dns = [[QNDnsManager alloc] init:array networkInfo:[QNNetworkInfo normal]];
builder.dns = dns;
//是否选择  https  上传
builder.useHttps = YES;
//设置断点续传
NSError *error;
 builder.recorder =  [QNFileRecorder fileRecorderWithFolder:@"保存目录" error:&error];
}];

另一个在线文档：http://cocoadocs.org/docsets/Qiniu/7.1.6/
变成了：
注意： 如使用最新版的sdk(7.1.4),可自动判断上传空间。按如下方式使用：
QNConfiguration *config =[QNConfiguration  	build:^(QNConfigurationBuilder *builder) {
  NSMutableArray *array = [[NSMutableArray alloc] init];
  [array addObject:[QNResolver systemResolver]];
  QNDnsManager *dns = [[QNDnsManager alloc] init:array networkInfo:[QNNetworkInfo normal]];//是否选择  https  上传
  builder.zone = [[QNAutoZone alloc] initWithHttps:YES dns:dns];//设置断点续传
  NSError *error;
  builder.recorder =  [QNFileRecorder fileRecorderWithFolder:@"保存目录" error:&error];}];

但我用的最新的Release 7.2.5，发现QNConfigurationBuilder中的dns属性已经移除，QNAutoZone.h也没开放出来，没法调用QNAutoZone类，所以Release 7.2.5版本没法按照上面两种版本进行设置。
请问现在Release 7.2.5该怎么设置呀？

**Comment by liunianhuaguoyanxi** [comment]
最新版中QNAutoZone 中没有“initWithHttps：dns：”

**Comment by leleliu008** [comment]
如使用最新版的sdk，默认自动判断上传空间。不要设置build.zone即可。

**Comment by bachue** [comment]
新的版本可以支持
