### ISSUE TITLE
上传不进入回调，一直打印BoringSSL

### ISSUE THREAD

**Issue by f2yu** [qiniu/objc-sdk#291]
4G状态下一直打印这个，换个网络或者其他手机在4G下没这个情况，关掉网络后会进入回调
[BoringSSL] boringssl_session_errorlog(236) [C30.1:2][0x10fcf5e00] [boringssl_session_write] SSL_ERROR_SYSCALL(5): operation

**Comment by YangSen-qn** [comment]
请升级到最新版本 @f2yu
