### ISSUE TITLE
cocoapods安装七牛安装不上

### ISSUE THREAD

**Issue by lovexioaxi21** [qiniu/objc-sdk#294]
pod install 提示以下问题：

[!] Error installing HappyDNS
[!] /usr/bin/git clone https://github.com/qiniu/happy-dns-objc.git /var/folders/jx/8vb3smz573g19vd9nvy952jh0000gn/T/d20190108-15264-o1j0fj --template= --single-branch --depth 1 --branch v0.3.14

Cloning into '/var/folders/jx/8vb3smz573g19vd9nvy952jh0000gn/T/d20190108-15264-o1j0fj'...
fatal: unable to access 'https://github.com/qiniu/happy-dns-objc.git/': Failed to connect to 127.0.0.1 port 1086: Connection refused

**Comment by YangSen-qn** [comment]
检查下cocopods 重新pod
