### ISSUE TITLE
并发上传，如何单个取消，和断点续传

### ISSUE THREAD

**Issue by chengzj456** [qiniu/objc-sdk#295]
1.只实例化一个QNUploadManager，如果并发上传，怎么设置多个QNFileRecorder
2.只实例化一个QNUploadOption，并发上传所有进度都会通过这个QNUploadOption回传，但是如何取消指定key的上传

**Comment by YangSen-qn** [comment]
1. 并发上传也只需要设置一个QNFileRecorder
2. 每一个上传都需要指定一个上传的option
