### ISSUE TITLE
HappyDNS在7.2.5的dependency中没有被去除

### ISSUE THREAD

**Issue by singleD** [qiniu/objc-sdk#298]
看代码的话，HappyDNS应该是被移除了，但是7.2.5的spec里面还存在对应的dependency

**Comment by carter2000** [comment]
感谢反馈，经过统计调研，我们确认 happydns 对改善 dns 解析成功率有明显帮助，在最新 7.4.1 版本中 happydns 已经重新引入。

当前有已知问题，会尽快修复：https://github.com/qiniu/objc-sdk/issues/339

**Comment by carter2000** [comment]
https://github.com/qiniu/objc-sdk/issues/339 问题已解决，最新推荐版本 7.4.2
