### ISSUE TITLE
增加iOS 7的后台运行支持

### ISSUE THREAD

**Issue by longbai** [qiniu/objc-sdk#3]
使用AFNetworking 的AFSessionManager 进行网络连接，支持后台运行时传输数据。

**Comment by longbai** [comment]
已经加入了 iOS 7.0 的session manager, 下一步 做后台支持。

**Comment by iBenjamin** [comment]
后台支持可以了吗？

**Comment by longbai** [comment]
#101

**Comment by longbai** [comment]
参考了 这几个，后台上传目前还不行，所以去掉。http://stackoverflow.com/questions/25660363/upload-tasks-from-nsdata-are-not-supported-in-background-sessions 
http://stackoverflow.com/questions/27154006/how-to-upload-task-in-background-using-afnetworking
http://openstackwiki.org/wiki/Wie_zum_Hochladen_von_Aufgabe_im_Hintergrund_unter_Verwendung_von_Afnetworking
