### ISSUE TITLE
7.2.6版本iOS13系统问题

### ISSUE THREAD

**Issue by WuXiaoTu** [qiniu/objc-sdk#306]
Qiniu7.2.6版本系统iOS13 上传视频的时候上传到百分之95的时候就卡住了，也就是QNUploadOption的percent回调0.95的时候就卡住了，卡住要等很久很久基本上要等2-3分钟之后控制台报了[E][tx_dr_thread.cpp, threadLoop, 390]:【DR】Idle time > 60s Close TCP这个之后才返回1.0才算上传完成。 请七牛大佬解决一下这个问题iOS13才会 13以上的系统不会。

**Comment by AbeiOS** [comment]
同样 7.2.6 的包，上传视频的时候可以呀~ @WuXiaoTu

**Comment by XiaopingSun** [comment]
> Qiniu7.2.6版本系统iOS13 上传视频的时候上传到百分之95的时候就卡住了，也就是QNUploadOption的percent回调0.95的时候就卡住了，卡住要等很久很久基本上要等2-3分钟之后控制台报了[E][tx_dr_thread.cpp, threadLoop, 390]:【DR】Idle time > 60s Close TCP这个之后才返回1.0才算上传完成。 请七牛大佬解决一下这个问题iOS13才会 13以上的系统不会。

你那里是必现的吗，具体复现的步骤麻烦描述下

**Comment by bachue** [comment]
由于 Issue 时间太久没有回复，关闭了，如果还有问题，可以 Reopen
