### ISSUE TITLE
断点上传问题

### ISSUE THREAD

**Issue by Daniel7919** [qiniu/objc-sdk#312]
您好  我这使用最新的7.3版本的七牛 按照文档上写的 设置断点续传  可是一直都无效，每次上传都是从0开始，能帮忙看下是什么问题么  以下是源码 不胜感激
![image](https://user-images.githubusercontent.com/56992239/71445539-998bc980-2755-11ea-893a-b711e2d69259.png)
![image](https://user-images.githubusercontent.com/56992239/71445548-a7d9e580-2755-11ea-9bba-081a01c2596f.png)

**Comment by YangSen-qn** [comment]
确认下两点信息：
1. cacheDir是否有 有效值
2. 每次上传的数据大小是否大于4M, 如果之前上传小于4M续传是会从0开始上传的。

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-949
