### ISSUE TITLE
iOS10.0 到 iOS10.2 版本崩溃

### ISSUE THREAD

**Issue by jiaxiaochao** [qiniu/objc-sdk#327]
<img width="1039" alt="截屏2020-05-18 下午7 39 03" src="https://user-images.githubusercontent.com/8316147/82209066-3c302900-993f-11ea-98b1-b2a717584f9e.png">

**Comment by XiaopingSun** [comment]
其他系统版本有问题吗

**Comment by jiaxiaochao** [comment]
没有统计到

**Comment by robaggio** [comment]
看起来 新版本v7.3.4已经修复了
https://github.com/qiniu/objc-sdk/commit/ebf95967f8f03ff8d33a8e3dbc02eecf7295e521

**Comment by NicolasKim** [comment]
@jiaxiaochao  更新了之后 这个问题还存在吗？

**Comment by jiaxiaochao** [comment]
用户的设备 没法测试了
