### ISSUE TITLE
变量名错误导致项目不能正常运行

### ISSUE THREAD

**Issue by SYFH** [qiniu/objc-sdk#338]
https://github.com/qiniu/objc-sdk/blob/6a46c8caf174b7d01bf4c80fa2ee5189118d6a0c/QiniuSDK/Http/Dns/QNDnsPrefetcher.m#L324

应该是 `defaultTtl`

**Comment by YangSen-qn** [comment]
感谢您提出的问题，这个问题已经处理，新版的SDK还在测试阶段，暂时的解决方案是修改pod，使SDK依赖于HappyDNS 0.3.16版本:
  pod 'Qiniu', "7.4.1"
  pod 'HappyDNS', "0.3.16"
