### ISSUE TITLE
httpDns新版变更defalutTtl---> defaultTtl

### ISSUE THREAD

**Issue by GitHubazuo** [qiniu/objc-sdk#339]
![image](https://user-images.githubusercontent.com/15389354/86987432-9d9aa880-c1c8-11ea-8116-374ac208c0d0.png)

**Comment by Neil20170223** [comment]
编译不过

**Comment by musicode** [comment]
能不能发个新版本紧急修复一下？

**Comment by musicode** [comment]
7.4.1 版本发布了 10 天，居然连这种拼写错误都不修复，七牛确实牛

**Comment by captain-black** [comment]
挺尴尬的。虽然自己改了一下代码就好，但是还是希望尽早修复一下吧。

**Comment by YangSen-qn** [comment]
感谢您提出的问题，这个问题已经处理，新版的SDK还在测试阶段，暂时的解决方案是修改pod，使SDK依赖于HappyDNS 0.3.16版本:
  pod 'Qiniu', "7.4.1"
  pod 'HappyDNS', "0.3.16"

**Comment by carter2000** [comment]
@captain-black 多谢反馈。我们会尽快修复发布。

**Comment by Mei-Zhao** [comment]
感谢反馈，我们新版本v7.4.2已经发布，修复了这个问题
