### ISSUE TITLE
Swift下出现连接错误

### ISSUE THREAD

**Issue by JeremyWei** [qiniu/objc-sdk#34]
环境：
* iOS SDK8.2
* Swift
* Xcode 6.2
* pod 'Qiniu', '~> 7.0'

错误信息：
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_QNResponseInfo", referenced from:
      __TMaCSo14QNResponseInfo in ImageComposeViewController.o
  "_OBJC_CLASS_$_QNUploadOption", referenced from:
      __TMaCSo14QNUploadOption in ImageComposeViewController.o
  "_OBJC_CLASS_$_QNUploadManager", referenced from:
      __TMaCSo15QNUploadManager in ImageComposeViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

应该是没有支持64bit

**Comment by forrest-mao** [comment]
这个是七牛的lib没有成功添加到项目中去，通过workspace进入 然后编译是否可行。

**Comment by JeremyWei** [comment]
是因为target的build setting中```HEADER_SEARCH_PATHS```的设置有问题，添加```$(inherited)```就OK了，多谢。

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9291555/46b223dc-43fa-11e5-8aba-c54e150f8843.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9291557/628b09ca-43fa-11e5-9cbe-f696729a2d85.png)

**Comment by chelsh** [comment]
Could not build module 'Qiniu'
'HappyDNS.h' file not found

**Comment by chelsh** [comment]
有遇到过吗，该怎么解决啊

**Comment by longbai** [comment]
happydns 在 https://github.com/qiniu/happy-dns-objc 下载
