### ISSUE TITLE
为什么会往沙盒不断地创建文件？

### ISSUE THREAD

**Issue by NicolasKim** [qiniu/objc-sdk#346]
请尽快修复此问题
![企业微信20200727105345](https://user-images.githubusercontent.com/10464215/88499175-b47a3100-cff7-11ea-8d90-ec243f8c6ac6.png)

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：TS-1001

**Comment by forrest-mao** [comment]
感谢提醒，预计在下个版本可以解决

**Comment by Mei-Zhao** [comment]
您好，我们已经发布新版本v7.4.3修复此问题
