### ISSUE TITLE
QNUploadInfoReporter NSFileHandle exception

### ISSUE THREAD

**Issue by Neil20170223** [qiniu/objc-sdk#351]
-[NSFileHandle writeData:] 写入失败会抛出异常

**Comment by forrest-mao** [comment]
内部issue：TS-1010

**Comment by XiaopingSun** [comment]
异常的crash堆栈有搜集到吗   您这边使用的sdk版本号是多少

**Comment by Neil20170223** [comment]
- Qiniu (7.4.3):
    - HappyDNS (~> 0.3.17)

<img width="706" alt="图片" src="https://user-images.githubusercontent.com/28893316/89999535-836d5200-dcc1-11ea-97ae-3a935715977e.png">

**Comment by XiaopingSun** [comment]
好的我们看下

**Comment by XiaopingSun** [comment]
代码已提交  预计下个版本会修复

**Comment by Mei-Zhao** [comment]
新版本7.4.4解决了这个问题
