### ISSUE TITLE
SDK Error

### ISSUE THREAD

**Issue by Vactorwang** [qiniu/objc-sdk#366]
![image](https://user-images.githubusercontent.com/31955601/93964901-579abd00-fd93-11ea-9a4a-ba5ceb03bbe0.png)
![image](https://user-images.githubusercontent.com/31955601/93964938-6a14f680-fd93-11ea-93dd-77a6ae10c596.png)
![image](https://user-images.githubusercontent.com/31955601/93965026-9fb9df80-fd93-11ea-8d09-bd3295d3a3b9.png)
![image](https://user-images.githubusercontent.com/31955601/93965066-ba8c5400-fd93-11ea-9b9d-a18808d82d7a.png)
 
xcode 12  
sdk 8.0.2
 这些错误能处理一下么？集成了SDK就开始报这些错误，好几个版本了。还有拼写错误。。。

**Comment by YangSen-qn** [comment]
@Vactorwang 麻烦查下依赖的HappyDns版本，QiNiu SDK v8.0.2 依赖 HappyDns v0.3.17
