### ISSUE TITLE
'HappyDNS/HappyDNS.h' file not found

### ISSUE THREAD

**Issue by Gio7** [qiniu/objc-sdk#369]
我使用的是Xcode 11.6，swift5.1
下载了QiniuSDK和HappyDNS，导入到项目中，编译报错。
'HappyDNS/HappyDNS.h' file not found 这个类报错，'HappyDNS/HappyDNS.h' file not found

我没使用CocoaPods

**Comment by YangSen-qn** [comment]
你是引入了两个SDK工程，还是直接复制两个SDK工程的代码到你的项目里呢？

**Comment by Gio7** [comment]
> @Gio7 你是引入了两个SDK工程，还是直接复制两个SDK工程的代码到你的项目里呢？

复制的，我没用cocoapods，所以引入不了。

**Comment by Gio7** [comment]
@YangSen-qn  复制的，我用的Carthage，引入不了。

**Comment by YangSen-qn** [comment]
@Gio7 复制的话需要修改引入方式，修改QiniuSD引入HappyDNS代码，使用import "HappyDNS.h"

**Comment by Gio7** [comment]
换了CocoaPods，没用Carthage了
