### ISSUE TITLE
反复报SSL的错 

### ISSUE THREAD

**Issue by ymyesman** [qiniu/objc-sdk#377]
"发生了SSL错误，无法建立与该服务器的安全连接。" UserInfo={NSErrorFailingURLStringKey=https://applog.uc.cn/collect?app=28ef1713347d&uuid=0B7A1005-20D4-48F4-9F38-F22FAFDC310C&enc=aes&chk=6292d381&zip=gzip&vno=1606450945744, NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <D4468BFD-BC2D-4E66-909C-D9FD44581B37>.<179>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <D4468BFD-BC2D-4E66-909C-D9FD44581B37>.<179>"

**Comment by bachue** [comment]
@ymyesman  看上去这个错误和我们没有关系，`applog.uc.cn` 并不是我们的服务器地址

**Comment by myDonghao** [comment]
我也遇到了这个问题，感觉好奇怪！也不知道具体是那个库里是使用的这个网址来上传日志的

**Comment by bachue** [comment]
@ymyesman @myDonghao uc.cn 是 uc 浏览器的域名
