### ISSUE TITLE
iOS 14 对象存储会弹出请求本地网络访问权限的窗,可否取消此权限请求弹窗?

### ISSUE THREAD

**Issue by program-APE** [qiniu/objc-sdk#378]
Device: iPhone 11
iOS Version: iOS 14.1
当使用对象存储上传图片时会弹出会弹出请求本地网络访问权限的窗口
相关类: QNUploadManager
相关方法: - (void)putFile:(NSString *)filePath
            key:(NSString *)key
          token:(NSString *)token
       complete:(QNUpCompletionHandler)completionHandler
         option:(QNUploadOption *)option;

**Comment by YangSen-qn** [comment]
@program-APE 当前的SDK不会触发这个弹窗，取消此弹窗不会影响上传。

**Comment by program-APE** [comment]
> @program-APE 当前的SDK不会触发这个弹窗，取消此弹窗不会影响上传。

我清楚这个不会影响上传,目前的现象是使用 Qiniu SDK 上传图片就会弹这个窗,我之前用的 Qiniu SDK 版本是 8.0,后来升级到了 8.0.5 还是会弹出这个窗

**Comment by YangSen-qn** [comment]
> > @program-APE 当前的SDK不会触发这个弹窗，取消此弹窗不会影响上传。
> 
> 我清楚这个不会影响上传,目前的现象是使用 Qiniu SDK 上传图片就会弹这个窗,我之前用的 Qiniu SDK 版本是 8.0,后来升级到了 8.0.5 还是会弹出这个窗

你可以使用我们的demo测试下

**Comment by program-APE** [comment]
> > > @program-APE 当前的SDK不会触发这个弹窗，取消此弹窗不会影响上传。
> > 
> > 
> > 我清楚这个不会影响上传,目前的现象是使用 Qiniu SDK 上传图片就会弹这个窗,我之前用的 Qiniu SDK 版本是 8.0,后来升级到了 8.0.5 还是会弹出这个窗
> 
> 你可以使用我们的demo测试下

您好 测试结果如下 [Demo 权限访问截图](https://s3.ax1x.com/2020/12/02/DICL7Q.png)

**Comment by YangSen-qn** [comment]
> > > > @program-APE 当前的SDK不会触发这个弹窗，取消此弹窗不会影响上传。
> > > 
> > > 
> > > 我清楚这个不会影响上传,目前的现象是使用 Qiniu SDK 上传图片就会弹这个窗,我之前用的 Qiniu SDK 版本是 8.0,后来升级到了 8.0.5 还是会弹出这个窗
> > 
> > 
> > 你可以使用我们的demo测试下
> 
> 您好 测试结果如下 [Demo 权限访问截图](https://s3.ax1x.com/2020/12/02/DICL7Q.png)

demo 的代码有修改吗

**Comment by program-APE** [comment]
修改了 PodFile, 没有使用本地路径 使用的是 pod 'Qiniu'(下载下来的是8.0.5版本)
删除了这行
` #import "Configure.h" // 测试参数配置，暂时只有token，可删除
`
和 UploadResource_49M.zip 这个找不到的文件

替换了我自己的 Token
```
- (void)uploadImageToQNFilePath:(NSString *)filePath {
    
    self.token = @" 我的 token"
```

**Comment by YangSen-qn** [comment]
> 修改了 PodFile, 没有使用本地路径 使用的是 pod 'Qiniu'(下载下来的是8.0.5版本)
> 删除了这行
> `#import "Configure.h" // 测试参数配置，暂时只有token，可删除`
> 和 UploadResource_49M.zip 这个找不到的文件
> 
> 替换了我自己的 Token
> 
> ```
> - (void)uploadImageToQNFilePath:(NSString *)filePath {
>     
>     self.token = @" 我的 token"
> ```

我们这边在iOS14的多款手机上测试均没有复现。我们的SDK只需要有网络即可，不需要其他权限。
您那边也可以测试下，如果拒绝授权是否上传失败，如果一次上传可以成功，那就说明没有问题。

**Comment by program-APE** [comment]
上传功能是好的,只是不希望有这个权限请求,因为涉及到权限请求就要有对应说明,审核时会因为这个被拒.

**Comment by YangSen-qn** [comment]
在info.plist文件上加上权限相应声明应该就没有问题了

**Comment by program-APE** [comment]
嗯 这个我清楚 只是觉得没用到这个权限 还需要请求有些奇怪
