### ISSUE TITLE
-[__NSArrayM objectAtIndex:]: index 7 beyond bounds [0 .. 6]

### ISSUE THREAD

**Issue by NicolasKim** [qiniu/objc-sdk#385]
设备机型:iPhone12
系统版本:14.2 (18B111)

NSRangeException

*** -[__NSArrayM objectAtIndex:]: index 7 beyond bounds [0 .. 6]

库 | 堆栈
-- | --
0 CoreFoundation | ___exceptionPreprocess + 220
1 libobjc.A.dylib | objc_exception_throw + 60
2 CoreFoundation | -[__NSCFString characterAtIndex:].cold.1
3 CoreFoundation | __CFDataInit
4 CoreFoundation | -[NSMutableArray removeObject:] + 140
5 Qiniu | -[QNAutoZone destroyUploadRequestTransaction:] + 84
6 Qiniu | __26-[QNAutoZone preQuery:on:]_block_invoke + 684
7 Qiniu | -[QNHttpRegionRequest complete:response:complete:] + 140
8 Qiniu | __95-[QNHttpRegionRequest performRequest:action:headers:method:body:shouldRetry:progress:complete:]_block_invoke + 636
9 Qiniu | -[QNHttpSingleRequest complete:server:response:requestMetrics:complete:] + 216
10 Qiniu | __83-[QNHttpSingleRequest retryRequest:server:toSkipDns:shouldRetry:progress:complete:]_block_invoke.43 + 876
11 Qiniu | -[QNUploadSystemClient URLSession:task:didCompleteWithError:] + 780
12 CFNetwork | _CFNetworkHTTPConnectionCacheSetLimit + 153904
13 libdispatch.dylib | __dispatch_call_block_and_release + 32
14 libdispatch.dylib | __dispatch_client_callout + 20
15 libdispatch.dylib | __dispatch_lane_serial_drain + 580
16 libdispatch.dylib | __dispatch_lane_invoke + 460
17 libdispatch.dylib | __dispatch_workloop_worker_thread + 708
18 libsystem_pthread.dylib | _pthread_wqthread + 276
19 libsystem_pthread.dylib | start_wqthread + 8

**Comment by NicolasKim** [comment]
> @NicolasKim SDK 版本号是多少？

8.1.0

**Comment by YangSen-qn** [comment]
@NicolasKim 请升级 SDK 到 v8.2.1
