### ISSUE TITLE
recorderKeyGen 设置无效

### ISSUE THREAD

**Issue by xuebo2215** [qiniu/objc-sdk#388]
builder.recorderKeyGen = ^NSString*(NSString*key,NSString*path){
        return FormatString(@"QiniuUploadRecorderKey_%@",key);
};
QNConfiguration中设置recorderKeyGen回调不生效。
QNRecorderDelegate代理
- (NSError *)set:(NSString *)key data:(NSData *)value;
- 等方法中返回的key还是上传文件的key，并不是recorderKeyGen生成的。

**Comment by YangSen-qn** [comment]
> builder.recorderKeyGen = ^NSString*(NSString_key,NSString_path){
> return FormatString(@"QiniuUploadRecorderKey_%@",key);
> };
> QNConfiguration中设置recorderKeyGen回调不生效。
> QNRecorderDelegate代理
> 
> * (NSError *)set:(NSString *)key data:(NSData *)value;
> * 等方法中返回的key还是上传文件的key，并不是recorderKeyGen生成的。

感谢您的反馈，我们会尽快处理

**Comment by YangSen-qn** [comment]
@xuebo2215 v8.2.1 处理了这个问题
