### ISSUE TITLE
PHAsset上传错误

### ISSUE THREAD

**Issue by KerwinCheung** [qiniu/objc-sdk#389]
设备机型:iPhone12
系统版本:14.4
编码语言:Swift
SDK版本:8.2.1
putPHAsset函数报status: -4错误,Domain=NSCocoaErrorDomain Code=256 "未能打开该文件。"
请问这个有解决办法吗

**Comment by YangSen-qn** [comment]
> 设备机型:iPhone12
> 系统版本:14.4
> 编码语言:Swift
> SDK版本:8.2.1
> putPHAsset函数报status: -4错误,Domain=NSCocoaErrorDomain Code=256 "未能打开该文件。"
> 请问这个有解决办法吗

@KerwinCheung 请使用工程里的 demo 测试下，是否有相同的问题

**Comment by KerwinCheung** [comment]
emmm 虽然这个函数调用失败 不过使用phasserresource这个倒是可以。。没什么影响多步操作。
