### ISSUE TITLE
NSURLErrorDomain错误-1001。

### ISSUE THREAD

**Issue by zzzzzyijie** [qiniu/objc-sdk#398]
版本： "Qiniu", "~> 8.1.2"

最近频繁出现 【未能完成操作。（NSURLErrorDomain错误-1001。）】
或 【未能完成操作。（“qiniu.com”错误 -1009。】
或 【请求超时】用户返回说 好几分钟

啥问题吗？

**Comment by zzzzzyijie** [comment]
以及【NSError(qiniu.com:401)  未能完成操作。（qiniu.com错误401。】

**Comment by YangSen-qn** [comment]
> 版本： "Qiniu", "~> 8.1.2"
> 
> 最近频繁出现 【未能完成操作。（NSURLErrorDomain错误-1001。）】
> 或 【未能完成操作。（“qiniu.com”错误 -1009。】
> 或 【请求超时】用户返回说 好几分钟
> 
> 啥问题吗？

-1001 很大原因是用户网络问题，也可能是 dns 缓存问题，建议升级 8.3.1 SDK  对此有优化。
-1009 属于用户网络问题。
等待时间长主要是上传失败重试导致，可降低重试次数以及缩短请求超时。

**Comment by YangSen-qn** [comment]
> 以及【NSError(qiniu.com:401) 未能完成操作。（qiniu.com错误401。】

401 token 异常，需要可借助于 error 描述信息；
错误码可参考链接：https://developer.qiniu.com/kodo/3928/error-responses

**Comment by zzzzzyijie** [comment]
但是，有几个疑问：
1. 这个情况突然这两天才开始出现 , 尤其是iPad用户（基本上）
2. 1009这个网络问题也太频繁了吧，这个目前统计到了2500次+
3. 关于等待时间长的 ，我这边没有特别的设置，我看SDK的默认重试0次的，所以感觉这个不太准
4. 401token异常目前出现100次左右

**Comment by zzzzzyijie** [comment]
更正 SDK默认为 1 次。retryMax = 1

**Comment by YangSen-qn** [comment]
> 但是，有几个疑问：
> 
> 1. 这个情况突然这两天才开始出现 , 尤其是iPad用户（基本上）
> 2. 1009这个网络问题也太频繁了吧，这个目前统计到了2500次+
> 3. 关于等待时间长的 ，我这边没有特别的设置，我看SDK的默认重试0次的，所以感觉这个不太准
> 4. 401token异常目前出现100次左右

- 针对第一个问题，建议您升级 SDK 到 8.3.1
- -1009 很大几率是用户网络问题，针对第一个问题
- 重试次数只是单个 host 的重试次数，0代表不重试。实际等待时间根据请求数决定的。
- 401 问题可以提供下上传的 key 吗

**Comment by zzzzzyijie** [comment]
最开始使用七牛客户端SDK是为了兼容海外用户的； 
但确实太不稳定了，虽然1009是网络问题，但发生次数多，且用户访问其他页面/App没问题时，就很难有说服力了；
现在先改回走后端服务器api来传图片了。

**Comment by bachue** [comment]
@zzzzzyijie 对于海外用户情况，建议传输到海外存储空间，可以减少网络失败的概率。
