### ISSUE TITLE
*** -[NSURL initWithString:relativeToURL:]: nil string parameter 崩溃

### ISSUE THREAD

**Issue by lyandy** [qiniu/objc-sdk#399]
崩溃sentry记录：https://sentry-ios.mm.taou.com/share/issue/e196791e90ec4ab89cbdc639967faa8f/
version: 7.3.0

原因：
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/3918529/129691356-88ae3fbd-741b-4ffd-9535-fa2dbdef9e52.png">
此处url如果为nil，就会崩溃。

继续看前面调用栈：使用的是 uphost 变量
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/3918529/129691494-f9c47e92-c4bb-46e7-9693-d19f9022991f.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/3918529/129691532-d05f6803-3121-48ef-88b2-ea8348413767.png">

再看 uphost 的生成方法：
<img width="793" alt="image" src="https://user-images.githubusercontent.com/3918529/129691757-27658c0b-8822-4d77-a387-6805b8f0e4d3.png">
明显会出现返回nil的情况，进而导致 NSURL *URL = [[NSURL alloc] initWithString:url]; 调用崩溃

最新版本依然在用 [[NSURL alloc] initWithString:url]，是否考虑更换？

**Comment by YangSen-qn** [comment]
新版本在使用 host 之前会做判空处理，建议您升级最新版本(8.3.1)。

感谢您的反馈！

**Comment by lyandy** [comment]
> 新版本在使用 host 之前会做判空处理，建议您升级最新版本(8.3.1)。
> 
> 感谢您的反馈！

看到了

![image](https://user-images.githubusercontent.com/3918529/129834016-ea029a99-d3e6-43f9-8b47-c97e57a4e039.png)

之前引起崩溃的方法也不再调用了。给力👍🏻
