### ISSUE TITLE
XCode14打包上传警告

### ISSUE THREAD

**Issue by kylechandev** [qiniu/objc-sdk#416]
升级XCode到14后，打包上传appstore最后报了个警告：
`The app references non-public selectors in Payload/xxx.app/Frameworks/Qiniu.framework/Qiniu: lookup:`

之前在13的时候没问题，版本是`8.4.4`

**Comment by YangSen-qn** [comment]
@kylechandev 能提供下更详细的信息吗？比如 lookup 后面的信息。

**Comment by kylechandev** [comment]
完整的信息就是这样的，我google了一下应该是函数名和apple内部的某个私有方法重名了，我是用的cocoapods集成的，然后unlock了一下file，把所有lookup的函数名改成了lookupQINIU这个警告就消失了。因为这个警告最终提交applestore审核的话会被拒，理由就是使用了非公开的函数

**Comment by YangSen-qn** [comment]
@kylechandev 

好的，感谢您的反馈！！！

**Comment by bachue** [comment]
在 [v8.5.0](https://github.com/qiniu/objc-sdk/releases/tag/v8.5.0) 里已经解决
