### ISSUE TITLE
Proxy 设置为 nil 的情况下，不走系统设置的代理

### ISSUE THREAD

**Issue by cntrump** [qiniu/objc-sdk#450]
代码逻辑里面并没有类似 `CFNetworkCopySystemProxySettings` 读取系统代理的逻辑。

**Comment by YangSen-qn** [comment]
> 代码逻辑里面并没有类似 `CFNetworkCopySystemProxySettings` 读取系统代理的逻辑。

感谢反馈，当前临时解决方案为关闭 DNS 预解析功能：
```
kQNGlobalConfiguration.isDnsOpen = NO;
```
