### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by yeby** [qiniu/objc-sdk#48]
Undefined symbols for architecture armv7:
  "_kQNInvalidArgument", referenced from:
      -[QNFormUploadTest testNoData] in QNFormUploadTest.o
      -[QNFormUploadTest testNoFile] in QNFormUploadTest.o
      -[QNFormUploadTest testNoToken] in QNFormUploadTest.o
  "_kQNRequestCancelled", referenced from:
      -[QNFileRecorderTest template:pos:] in QNFileRecorderTest.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by longbai** [comment]
请问是通过什么方式编译，看起来是没有引用到七牛的library
