### ISSUE TITLE
swift下通过桥接引用七牛sdk，出现Could not build module 'Qiniu'

### ISSUE THREAD

**Issue by chelsh** [qiniu/objc-sdk#59]
通过这个安装：
pod 'Qiniu', '~> 7.0'
pod 'AFNetworking', '~> 2.0'

安装后：
![image](https://cloud.githubusercontent.com/assets/10752360/9292364/99dd2576-4426-11e5-88ad-877b526f0c3f.png)

然后在桥接文件加入：

![image](https://cloud.githubusercontent.com/assets/10752360/9292362/8b1f596e-4426-11e5-92bf-39d9760b1a93.png)

出现了：
1。Could not build module 'Qiniu'
2。'HappyDNS.h' file not found

**Comment by longbai** [comment]
pod 'HappyDNS', '>= 0.1'

麻烦加下这个

**Comment by chelsh** [comment]
好的，但是为何报这个错误呢：1。Could not build module 'Qiniu'

**Comment by longbai** [comment]
1 依赖于 2 ；应该pod update 会自动解决依赖吧，happydns 已经写入了 podspec, 按理不应该出现这个问题。

**Comment by chelsh** [comment]
加上：pod 'HappyDNS', '>= 0.1'  然后 pod install  然后 pod update，还是这样的错误


![image](https://cloud.githubusercontent.com/assets/10752360/9296736/fe1216ce-44c5-11e5-8943-4141637a179d.png)

**Comment by longbai** [comment]
奇怪，我也不知道了，pod 版本是多少？是否可以把 https://github.com/qiniu/happy-dns-objc 这个项目代码直接copy下来？

**Comment by chelsh** [comment]
$ pod --version
0.36.4

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9301115/a07a638e-44fe-11e5-8d52-51bd84daa2dd.png)

**Comment by chelsh** [comment]
把源码下载下来，直接copy到pod目录下，还是一样 。

**Comment by longbai** [comment]
奇怪了，我仔细查下

**Comment by chelsh** [comment]
hello，怎么样呢：），你建swift工程，调用七牛的sdk，可以调用成功吗？

**Comment by michaelxxw** [comment]
碰到同样问题

**Comment by chelsh** [comment]
怎么样呢 ，还是一样的错误。@longbai

**Comment by michaelxxw** [comment]
如果不用断点续传，可以用6.x的版本，昨天，我用6.x的版本重新打了个通用的静态库，7.x的应该也可以

**Comment by longbai** [comment]
麻烦 先 指定 v7.0.11.1 这个版本。 这个问题我正在看

**Comment by longbai** [comment]
6.x 不建议使用， @michaelxxw

**Comment by michaelxxw** [comment]
用了会有什么问题么？主要急用

**Comment by chelsh** [comment]
v7.0.11.1 这个版本  可以使用HappyDNS吗？

**Comment by longbai** [comment]
@chelsh 没有集成

**Comment by longbai** [comment]
@michaelxxw 不会有什么问题，只是不会添加新功能了

**Comment by chelsh** [comment]
那最新版本的那个问题 大概什么时候会解决掉呢？ 还有 会出纯swift版本的七牛sdk吗

**Comment by longbai** [comment]
@chelsh 抱歉 我尽快解决，最迟这周会解决掉。纯swift 版本肯定会出来的，正在规划。

**Comment by chelsh** [comment]
好的，谢谢啊：）

**Comment by chelsh** [comment]
可以安装了吗 @longbai

**Comment by sutra** [comment]
You should change
`#import "HappyDNS.h"` to `#import "HappyDNS/HappyDNS.h"`.

**Comment by longbai** [comment]
多谢 sutra，应该使用 "HappyDNS.h" 或者 <HappyDNS/HappyDNS.h>

**Comment by longbai** [comment]
cocoapods 0.38 0.38.2
```
#import <AFNetworking/AFNetworking.h>
#import <Qiniu/QiniuSDK.h>
#import <HappyDNS/HappyDNS.h>
```

测试正常

**Comment by longbai** [comment]
项目地址 http://w1.qiniucdn.com/test.tgz

**Comment by longbai** [comment]
哦，还有确认下是否打开的是workspace 进行编译。

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9566886/4b1616f8-4f4a-11e5-901e-e2c2d139e8d5.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9566889/5fc7ceb6-4f4a-11e5-9b28-39496480f65c.png)

**Comment by chelsh** [comment]
以上是可以的。

**Comment by chelsh** [comment]
加了：use_frameworks!    pod 'SwiftyJSON', '~> 2.2.0'
pod 'Kingfisher', '~> 1.4'  就报错了。SwiftyJSON是用于解析json的，Kingfisher是用于图片的。
![image](https://cloud.githubusercontent.com/assets/10752360/9566909/4f4293f4-4f4b-11e5-901b-144258346530.png)

**Comment by chelsh** [comment]
应该是 use_frameworks!   这个引起的：（

**Comment by chelsh** [comment]
我又测试了一遍：我的整个工程是基于swift语言的，由于后续要用到SwiftyJSON包，这个包是基于swift语言的，它要求加入 use_frameworks!   ，可是我都没加SwiftyJSON包，只加了use_frameworks! ，  qiniu SDK就发生错误了，而 AFNetworking SDK都没有发生错误，是不是qiniu SDK兼容性没做好呢？

![image](https://cloud.githubusercontent.com/assets/10752360/9567049/5ed623d6-4f4f-11e5-9c1a-8a673ba75aad.png)

**Comment by chelsh** [comment]
我的pod版本：
![image](https://cloud.githubusercontent.com/assets/10752360/9567055/9df60784-4f4f-11e5-9f1c-f3ba3959a8be.png)

**Comment by chelsh** [comment]
CocoaPods：
![image](https://cloud.githubusercontent.com/assets/10752360/9567060/ca16a27e-4f4f-11e5-9ee7-863ccc0d9370.png)

**Comment by sutra** [comment]
> cocoapods 0.38 0.38.2
> 
> #import <AFNetworking/AFNetworking.h>
> #import <Qiniu/QiniuSDK.h>
> #import <HappyDNS/HappyDNS.h>
> 测试正常

其实你们误解了我的意思，我的意思是在 QiniuSDK 里面需要把
`#import "HappyDns.h"` 改成 `#import "HappyDns/HappyDns.h"` .

我不知道为什么，但是我这样改了之后可以用。
我就是在我自己的项目里 pod update 完成后，再修改了我的项目目录下的 `Pods/Qiniu/QiniuSDK/StorageQNConfiguration.h` 中的 `#import "HappyDns.h"` 后解决的。

**Comment by longbai** [comment]
@sutra 谢谢，那两个小写的问题 我已经合并了你的PR。 "" 貌似是查找本地的header，所以"HappyDns.h" 也可以work的, <HappyDns.h"> 不行

**Comment by chelsh** [comment]
好的。同时CocoaPods作者给的回复：https://github.com/CocoaPods/CocoaPods/issues/4107#event-396023374

Looks like the Qiniu SDK is using quoted imports for its dependencies, so it'll need to be updated upstream to work as a framework. You should also get rid of your bridging header and use import directly from Swift.

**Comment by longbai** [comment]
@chelsh 十分感谢，我这边推进下把库搞成framework

**Comment by chelsh** [comment]
奇怪没有 QNUploadManager，QNDnsManager就有。

![image](https://cloud.githubusercontent.com/assets/10752360/9653259/e1004b4a-5254-11e5-96d8-4c61a0796fd6.png)


![image](https://cloud.githubusercontent.com/assets/10752360/9653292/0659e856-5255-11e5-97db-523f4f597bae.png)

![image](https://cloud.githubusercontent.com/assets/10752360/9653296/186005da-5255-11e5-8856-d7fedbcde37d.png)

**Comment by chelsh** [comment]
可是pod install后的包里面就有 ：
![image](https://cloud.githubusercontent.com/assets/10752360/9653356/81777184-5255-11e5-81d3-9bd2a2b69383.png)

**Comment by sutra** [comment]
加上`import Qiniu`试试。

**Comment by chelsh** [comment]
你那边可以？ @sutra

**Comment by chelsh** [comment]
加上import Qiniu   可以了。 @sutra

**Comment by lijinchao2007** [comment]
pod "TRQiniu", "7.0.15"
我切到的一个版本，能够    use_frameworks!
https://github.com/PodRepo/objc-sdk

我只是很简单的把HappyDns隐藏在.m文件中。不要把HappyDns暴露出去

**Comment by longbai** [comment]
@lijinchao2007 多谢，我研究下

**Comment by yxztj** [comment]
我也遇到了同样的问题
版本7.0.12 使用cocoapods 也安装了HappyDNS(应该是dependency自动安装)
同样在QNConfiguration.h里面把
#import "HappyDNS.h" 
改成
#import "HappyDns/HappyDNS.h"
就OK了

**Comment by banxi1988** [comment]
本来我是想在 bridge-header.h 中添加 但是 都报错，
然后发现可以直接在 Swift 中导入，但是 QNStats.h 中报编译错误。
于是。
进行了如下修改即可。

```objc
@import AFNetworking;
@import HappyDNS;
//#import "AFNetworking.h"
//#import "HappyDns.h"
```

**Comment by longbai** [comment]
@banxi1988 刚才做了下升级，应该没有这个问题了

**Comment by banxi1988** [comment]
@longbai  我就是使用的最新版本的呢。刚刚更新，Qiniu 7.0.14

**Comment by longbai** [comment]
@banxi1988 我刚发布的 7.0.15

**Comment by banxi1988** [comment]
@longbai 嗯，可能是 cocoapods 库还没有来得及更新。我再试试吧。
