### ISSUE TITLE
七牛 SDK 中的AFNetworking 和 我们项目中的 AFNetworking 冲突

### ISSUE THREAD

**Issue by JasperYanky** [qiniu/objc-sdk#61]
用 pod 把 SDK 引入后 一堆 linker command failed with exit code 1   的错误  都是 AF 的错误~  ，求解

**Comment by longbai** [comment]
1.x 的么？

**Comment by JasperYanky** [comment]
不是  我们 AF 直接导源码进工程的；后来全部用 pod 了  就没问题了
