### ISSUE TITLE
pod "Qiniu" 编译不过

### ISSUE THREAD

**Issue by yuanyong** [qiniu/objc-sdk#64]
QNConfiguration.h 文件报错：
#import "HappyDNS.h"

https://github.com/qiniu/objc-sdk/releases/tag/v7.0.12
Release Note写的使用 happydns 进行解析，不知道为啥还是直接引用

**Comment by longbai** [comment]
cocoapod的版本是多少？

**Comment by yuanyong** [comment]
0.38

**Comment by longbai** [comment]
麻烦 参考下 #59 看看，我这边都是好好的

**Comment by longbai** [comment]
7.0.13 已经处理好
