### ISSUE TITLE
Swift 2.0上传文件回调问题

### ISSUE THREAD

**Issue by liufengting** [qiniu/objc-sdk#67]
upManager.putData(ImageData, key: self.getRandomKey(), token: token, complete: { (info:QNResponseInfo!, key:String!, resp:[NSObject : AnyObject]!) -> Void in
//上传成功后resp 为空
            }, option: QNUploadOption(mime: "text/plain", progressHandler: { (key:String!, percent:Float) -> Void in
                }, params: nil, checkCrc: true, cancellationSignal: nil))

**Comment by longbai** [comment]
我们在看这个问题

**Comment by liujunior** [comment]
请问大概什么时候能够解决呢？

**Comment by jiaojunjiahanlin** [comment]
您好：你在获取的上传token中是否设置了callbackbody和callbackurl的信息。如果设置了，先删除。然后重新生成token来上传测试。如果成功了，说明是设置参数的错误，你可以自己调整下参数。之前遇到过类似的问题，responseinfo中是200，但是response没有返回。这个问题不是七牛的问题。七牛是可以正常响应的，查过日志，也是完全没问题的。建议你用pod安装七牛依赖。不要用导入源码的方式。关掉一切的代理重新测试下。有问题可以再联系。也可以直接去七牛的账号后台，提交工单。

**Comment by liujunior** [comment]
我用相同的代码在Swift1.2Xcode6.3.1以及Swift2.0Xcode7.0下测试了，发现Swift2.0Xcode7.0下确实无法回调，而在Swift1.2下正常。请问这个问题真实存在吗？

**Comment by jiaojunjiahanlin** [comment]
你看下是不是ios限制了http链接的请求。http://blog.csdn.net/guoer9973/article/details/48622823
按照这个文档配置下。看看是否还是有问题。如果还存在，直接加我qq，1204289885
