### ISSUE TITLE
AFNetworking1.x Branch分支UTF8 Encode Error

### ISSUE THREAD

**Issue by syljay0508** [qiniu/objc-sdk#68]
今天你们Server出问题暴露出来这个分支的crash，master上看log修复了，希望贵司能把这个分支的问题也fix一下

**Comment by zhuangya** [comment]
https://github.com/qiniu/objc-sdk/blob/c79f51077e2e6282184fda0725f7b641ff547789/QiniuSDK/Http/QNResponseInfo.m#L75

问题出在这里，现在我们的 app 在持续的崩溃 TT TT

**Comment by longbai** [comment]
实在抱歉，真是很抱歉

**Comment by longbai** [comment]
fixed #69
