### ISSUE TITLE
我用的是Pod拉回来的AFNetworking 2.6.0，上传的时候报了这个错，怎么都上传不了

### ISSUE THREAD

**Issue by carusd** [qiniu/objc-sdk#75]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -streamStatus only defined for abstract class.  Define -[AFMultipartBodyStream streamStatus]!'
*** First throw call stack:
(0x181d182d8 0x1939ec0e4 0x181d18218 0x182c07f70 0x182c13a6c 0x1817088ac 0x181714ba8 0x181713d3c 0x181717670 0x18165373c 0x181bf8cdc 0x1816535e8 0x18165349c 0x1816532c8 0x181cd0240 0x181ccf4e4 0x181ccd594 0x181bf92d4 0x1816d6594 0x182c19db8 0x19424bdc8 0x19424bd24 0x194248ef8)

**Comment by longbai** [comment]
请把你的具体上传调用参数给下

**Comment by carusd** [comment]
不好意思我改了podfile但是没pod update，现在可以了

**Comment by carusd** [comment]
不好意思，是我改了podfile，但是没pod update，用的还是2.2.4
