### ISSUE TITLE
Upgrade to 7.0.14 occur duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by LuoLee** [qiniu/objc-sdk#91]
duplicate symbol _OBJC_CLASS_$_Reachability in:
    /Users/lilo/Library/Developer/Xcode/DerivedData/YDDApp-eumrpyxnudorchahpayajtodfrfp/Build/Intermediates/YDDApp.build/Debug-iphonesimulator/YDDApp.build/Objects-normal/x86_64/Reachability.o
    /Users/lilo/Library/Developer/Xcode/DerivedData/YDDApp-eumrpyxnudorchahpayajtodfrfp/Build/Products/Debug-iphonesimulator/libQiniu.a(Reachability.o)
duplicate symbol _OBJC_METACLASS_$_Reachability in:
    /Users/lilo/Library/Developer/Xcode/DerivedData/YDDApp-eumrpyxnudorchahpayajtodfrfp/Build/Intermediates/YDDApp.build/Debug-iphonesimulator/YDDApp.build/Objects-normal/x86_64/Reachability.o
    /Users/lilo/Library/Developer/Xcode/DerivedData/YDDApp-eumrpyxnudorchahpayajtodfrfp/Build/Products/Debug-iphonesimulator/libQiniu.a(Reachability.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

You may include some redundant libraries like Reachability etc into your staic library.

**Comment by longbai** [comment]
同名文件冲突，我来改下

**Comment by longbai** [comment]
fixed in #93
