### ISSUE TITLE
swift2 编译错误

### ISSUE THREAD

**Issue by dongkaipo** [qiniu/objc-sdk#94]
前几天pod安装的qiniusdk，今天早上pod udpate 发现程序无法运行了，QNStatus.h报错无法找到`"AFNetworking.h"` 刚才看了下git的更新时间是19小时前，是不是这次更新对qiniusdk产生了影响导致了无法编译，还是什么原因导致的无法运行？
![snip20151110_1](https://cloud.githubusercontent.com/assets/1720338/11055310/10a73246-87b1-11e5-85ad-29f2b2e7e5ab.png)

**Comment by longbai** [comment]
我来看下

**Comment by longbai** [comment]
fixed in #93

**Comment by dongkaipo** [comment]
多谢 @longbai 及时修复，:)
