### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by jasonwwang** [qiniu/objc-sdk#96]
目前一个项目，需要连续上传1M～3M的图片若干张。经测试发现，如果使用七牛SDK上传，每上传一张图片后，内存会增加1M~2M，导致上传20张图片后内存增加20M～40M。将上传方法改为 AFNetWorking的 上传方法，内存持续增加的问题消失。
项目中使用的七牛上传代码如下：
    QNUploadOption * option = [[QNUploadOption alloc] initWithProgressHandler:^(NSString *key, float percent) {
        if (progressBlcok) {
            progressBlcok(percent);
        }
    }];
    
    QNUploadManager * manager = [QNUploadManager sharedInstanceWithConfiguration:nil];
    __weak typeof(self) wself = self;
    [manager putData:imageData key:nil token:token complete:^(QNResponseInfo *info, NSString *key, NSDictionary *resp) {
        NSError * error = info.error;
        NSString * imageKey = resp[@"key"];
        if (wself.completedBlock) {
            wself.completedBlock(imageKey,error);
        }
        wself.completedBlock = nil;
        [wself done];
    } option:option]; 

使用AFNetworking的上传方法代码如下：
    AFHTTPRequestOperationManager *operationManager = [[AFHTTPRequestOperationManager alloc] initWithBaseURL:[NSURL URLWithString:@"http://upload.qiniu.com"]];
    NSMutableDictionary *parameters = [NSMutableDictionary dictionary];
    parameters[@"token"] = token;
    NSMutableURLRequest *request = [operationManager.requestSerializer
                                    multipartFormRequestWithMethod:@"POST"
                                    URLString:@"http://upload.qiniu.com"
                                    parameters:parameters
                                    constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
                                        [formData appendPartWithFileData:imageData name:@"file" fileName:@"file" mimeType:@"image/jpeg"];
                                    } error:nil];
    __weak typeof(self) wself = self;
    AFHTTPRequestOperation *operation = [operationManager HTTPRequestOperationWithRequest:request
                                                                                  success:^(AFHTTPRequestOperation *operation, id responseObject) {
                                                                                      

                                                                                      NSString * imageKey = responseObject[@"key"];
                                                                                      if (wself.completedBlock) {
                                                                                          wself.completedBlock(imageKey,nil);
                                                                                      }
                                                                                      wself.completedBlock = nil;
                                                                                      [wself done];

                                                                                  } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
                                                                                      if (wself.completedBlock) {
                                                                                          wself.completedBlock(nil,error);
                                                                                      }
                                                                                      wself.completedBlock = nil;
                                                                                      [wself done];
                                                                                  }];
    
    [operation setUploadProgressBlock:^(NSUInteger bytesWritten, long long totalBytesWritten, long long totalBytesExpectedToWrite) {
        if (progressBlcok) {
            double percent = totalBytesWritten * 1.0 / totalBytesExpectedToWrite;
            progressBlcok(percent);
        }
    }];

    [self.queue addOperation:operation];

**Comment by longbai** [comment]
请问版本是多少，之前的内存泄漏问题已经在7.0.13 版本修正

**Comment by jasonwwang** [comment]
SDK版本为7.0.15

**Comment by longbai** [comment]
我刚才又用leak 看了下，没发现问题，能给个demo项目吗？
