### ISSUE TITLE
支持 AFnetworking 3.0

### ISSUE THREAD

**Issue by longbai** [qiniu/objc-sdk#99]
另开一个分支 支持3.0

**Comment by ZuYuanZhou** [comment]
AFNetworking 3.0 的支持有进度表吗?

**Comment by ZuYuanZhou** [comment]
cocoapods 安装还是提示依赖于2.0

**Comment by wmbnm** [comment]
同问，什么时候去掉对2.0的依赖

**Comment by longbai** [comment]
见 https://github.com/qiniu/objc-sdk/tree/AFNetworking-3.x  目前AFN 用的还不是很广泛，需要再过一段时间，cocoapods 可以通过指定 git branch 来更新
